from __future__ import annotations

import hashlib
import json
from typing import Any, TypedDict


class FewShotExample(TypedDict):
    scenario: str
    input_payload: dict[str, Any]
    output_brief: dict[str, Any]


# text-first-v2 few-shot。以多輪 user/assistant 注入（見 llm.build_text_brief_messages）。
#
# input_payload 直接取自真實 DB 與 RAG 產出，與正式請求的 task_packet 完全同構
# （只把 daily_timeline 從 40 列裁到 12 列控制 token），這樣模型看到的範例輸入
# 才跟真實輸入長一樣，才學得到「這種時間軸要怎麼讀成 key_days」。
# output_brief 為人工撰寫並逐條核對：所有數字都出現在同一份 input_payload 裡、
# 所有 evidence_ids 都存在、不含技術指標名稱、不含法遵黑名單詞。
# 順序即注入順序，最典型的放最後。
FEW_SHOT_EXAMPLES: list[FewShotExample] = [{'scenario': '資料稀少且法人對作',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2615',
                             'as_of_date': '2026-03-20',
                             'timeline_trading_days': 40,
                             'analysis_language': 'zh-TW'},
                    'daily_timeline': [{'id': 'd_29',
                                        'date': '2026-03-05',
                                        'close': 78.7,
                                        'chg_pct': -3.44,
                                        'vol_lots': 52073,
                                        'vol_vs_ma5_pct': -15.0,
                                        'foreign_net_lots': -6944,
                                        'trust_net_lots': -101,
                                        'dealer_net_lots': -638,
                                        'rsi5': 48.6,
                                        'kd_k': 50.6,
                                        'macd_hist': 0.88,
                                        'vs_ma20_pct': 3.4,
                                        'news': []},
                                       {'id': 'd_30',
                                        'date': '2026-03-06',
                                        'close': 78.6,
                                        'chg_pct': -0.13,
                                        'vol_lots': 23639,
                                        'vol_vs_ma5_pct': -63.0,
                                        'foreign_net_lots': -1037,
                                        'trust_net_lots': -7,
                                        'dealer_net_lots': 1,
                                        'rsi5': 48.2,
                                        'kd_k': 39.5,
                                        'macd_hist': 0.65,
                                        'vs_ma20_pct': 2.9,
                                        'news': []},
                                       {'id': 'd_31',
                                        'date': '2026-03-09',
                                        'close': 81.1,
                                        'chg_pct': 3.18,
                                        'vol_lots': 75213,
                                        'vol_vs_ma5_pct': 5.0,
                                        'foreign_net_lots': -1027,
                                        'trust_net_lots': 4,
                                        'dealer_net_lots': 585,
                                        'rsi5': 59.0,
                                        'kd_k': 37.1,
                                        'macd_hist': 0.63,
                                        'vs_ma20_pct': 5.8,
                                        'news': []},
                                       {'id': 'd_32',
                                        'date': '2026-03-10',
                                        'close': 79.2,
                                        'chg_pct': -2.34,
                                        'vol_lots': 22157,
                                        'vol_vs_ma5_pct': -62.0,
                                        'foreign_net_lots': -1895,
                                        'trust_net_lots': -17,
                                        'dealer_net_lots': -468,
                                        'rsi5': 49.2,
                                        'kd_k': 31.6,
                                        'macd_hist': 0.46,
                                        'vs_ma20_pct': 3.0,
                                        'news': []},
                                       {'id': 'd_33',
                                        'date': '2026-03-11',
                                        'close': 79.8,
                                        'chg_pct': 0.76,
                                        'vol_lots': 17818,
                                        'vol_vs_ma5_pct': -53.0,
                                        'foreign_net_lots': 3029,
                                        'trust_net_lots': -37,
                                        'dealer_net_lots': 145,
                                        'rsi5': 52.3,
                                        'kd_k': 28.1,
                                        'macd_hist': 0.37,
                                        'vs_ma20_pct': 3.3,
                                        'news': []},
                                       {'id': 'd_34',
                                        'date': '2026-03-12',
                                        'close': 80.0,
                                        'chg_pct': 0.25,
                                        'vol_lots': 17798,
                                        'vol_vs_ma5_pct': -43.0,
                                        'foreign_net_lots': -923,
                                        'trust_net_lots': -18,
                                        'dealer_net_lots': -286,
                                        'rsi5': 53.5,
                                        'kd_k': 25.9,
                                        'macd_hist': 0.29,
                                        'vs_ma20_pct': 3.1,
                                        'news': []},
                                       {'id': 'd_35',
                                        'date': '2026-03-13',
                                        'close': 78.7,
                                        'chg_pct': -1.62,
                                        'vol_lots': 11394,
                                        'vol_vs_ma5_pct': -61.0,
                                        'foreign_net_lots': -2647,
                                        'trust_net_lots': -17,
                                        'dealer_net_lots': -110,
                                        'rsi5': 44.5,
                                        'kd_k': 21.7,
                                        'macd_hist': 0.14,
                                        'vs_ma20_pct': 1.1,
                                        'news': []},
                                       {'id': 'd_36',
                                        'date': '2026-03-16',
                                        'close': 78.9,
                                        'chg_pct': 0.25,
                                        'vol_lots': 16400,
                                        'vol_vs_ma5_pct': -4.0,
                                        'foreign_net_lots': 1959,
                                        'trust_net_lots': -72,
                                        'dealer_net_lots': 800,
                                        'rsi5': 46.2,
                                        'kd_k': 19.3,
                                        'macd_hist': 0.04,
                                        'vs_ma20_pct': 1.1,
                                        'news': []},
                                       {'id': 'd_37',
                                        'date': '2026-03-17',
                                        'close': 79.3,
                                        'chg_pct': 0.51,
                                        'vol_lots': 8467,
                                        'vol_vs_ma5_pct': -41.0,
                                        'foreign_net_lots': 572,
                                        'trust_net_lots': -74,
                                        'dealer_net_lots': 172,
                                        'rsi5': 50.2,
                                        'kd_k': 23.4,
                                        'macd_hist': -0.0,
                                        'vs_ma20_pct': 1.4,
                                        'news': []},
                                       {'id': 'd_38',
                                        'date': '2026-03-18',
                                        'close': 79.9,
                                        'chg_pct': 0.76,
                                        'vol_lots': 9540,
                                        'vol_vs_ma5_pct': -25.0,
                                        'foreign_net_lots': 351,
                                        'trust_net_lots': -18,
                                        'dealer_net_lots': 1064,
                                        'rsi5': 56.1,
                                        'kd_k': 29.0,
                                        'macd_hist': 0.0,
                                        'vs_ma20_pct': 1.7,
                                        'news': []},
                                       {'id': 'd_39',
                                        'date': '2026-03-19',
                                        'close': 78.5,
                                        'chg_pct': -1.75,
                                        'vol_lots': 11020,
                                        'vol_vs_ma5_pct': -3.0,
                                        'foreign_net_lots': -1519,
                                        'trust_net_lots': -13,
                                        'dealer_net_lots': 76,
                                        'rsi5': 41.6,
                                        'kd_k': 27.1,
                                        'macd_hist': -0.09,
                                        'vs_ma20_pct': -0.3,
                                        'news': []},
                                       {'id': 'd_40',
                                        'date': '2026-03-20',
                                        'close': 79.0,
                                        'chg_pct': 0.64,
                                        'vol_lots': 40808,
                                        'vol_vs_ma5_pct': 137.0,
                                        'foreign_net_lots': 34462,
                                        'trust_net_lots': -32739,
                                        'dealer_net_lots': -66,
                                        'rsi5': 47.6,
                                        'kd_k': 27.6,
                                        'macd_hist': -0.12,
                                        'vs_ma20_pct': 0.0,
                                        'news': []}],
                    'long_term_anchor': [{'id': 'lt_01',
                                          'field': 'high_1y',
                                          'date': '2025-05-22',
                                          'value': 126.5},
                                         {'id': 'lt_02',
                                          'field': 'low_1y',
                                          'date': '2025-04-09',
                                          'value': 61.1},
                                         {'id': 'lt_03',
                                          'field': 'close_pos_in_1y_pct',
                                          'date': '2026-03-20',
                                          'value': 27.4},
                                         {'id': 'lt_04',
                                          'field': 'vs_ma60_pct',
                                          'date': '2026-03-20',
                                          'value': 1.7},
                                         {'id': 'lt_05',
                                          'field': 'vs_ma240_pct',
                                          'date': '2026-03-20',
                                          'value': -6.6}],
                    'fundamental': [{'id': 'fd_01',
                                     'field': 'eps',
                                     'period': '2025Q3',
                                     'date': '2025-09-30',
                                     'value': 4.15,
                                     'qoq_pct': 992.1,
                                     'yoy_pct': -36.8,
                                     'last4q': [['2024Q4', 4.55],
                                                ['2025Q1', 3.11],
                                                ['2025Q2', 0.38],
                                                ['2025Q3', 4.15]]},
                                    {'id': 'fd_02',
                                     'field': 'gross_margin_pct',
                                     'period': '2025Q3',
                                     'date': '2025-09-30',
                                     'value': 30.6},
                                    {'id': 'fd_03',
                                     'field': 'operating_margin_pct',
                                     'period': '2025Q3',
                                     'date': '2025-09-30',
                                     'value': 25.6},
                                    {'id': 'fd_04',
                                     'field': 'revenue_monthly',
                                     'period': '2026-02',
                                     'value': 10580264000,
                                     'yoy_pct': -0.5,
                                     'mom_pct': -15.6,
                                     'yoy_last6': [['2025-09', -26.4],
                                                   ['2025-10', -24.2],
                                                   ['2025-11', -19.1],
                                                   ['2025-12', -16.1],
                                                   ['2026-01', -14.6],
                                                   ['2026-02', -0.5]]},
                                    {'id': 'fd_05',
                                     'field': 'per',
                                     'date': '2026-03-20',
                                     'value': 7.05,
                                     'pct_rank_1y': 99},
                                    {'id': 'fd_06',
                                     'field': 'pbr',
                                     'date': '2026-03-20',
                                     'value': 0.81,
                                     'pct_rank_1y': 9},
                                    {'id': 'fd_07',
                                     'field': 'dividend_yield',
                                     'date': '2026-03-20',
                                     'value': 3.8,
                                     'pct_rank_1y': 17}],
                    'news': [],
                    'missing_fields': ['近期新聞']},
  'output_brief': {'key_days': [{'id': 'kd_01',
                                 'date': '2026-03-09',
                                 'ref': 'd_31',
                                 'what': '這段期間唯一一次比較像樣的上漲，單日漲 3.18%，但成交量只比近五日平均多 5%，買方並沒有真的追上來。',
                                 'evidence_ids': ['d_31']},
                                {'id': 'kd_02',
                                 'date': '2026-03-13',
                                 'ref': 'd_35',
                                 'what': '股價下跌 1.62%，成交量比近五日平均萎縮 61%，跌勢是在幾乎沒有人交易的情況下發生的。',
                                 'evidence_ids': ['d_35']},
                                {'id': 'kd_03',
                                 'date': '2026-03-20',
                                 'ref': 'd_40',
                                 'what': '成交量突然比近五日平均放大 '
                                         '137%，外資買超三萬四千多張、投信同時賣超三萬兩千多張，兩邊幾乎對作，股價卻只微幅上漲 0.64%。',
                                 'evidence_ids': ['d_40']}],
                   'headline': '成交量長期低迷，最後一天外資與投信對作但股價幾乎沒動',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '三月二十日收在 79 元，正好貼著近一個月的平均價位，過去兩週幾乎都在小幅上下之間來回。',
                                       'direction': 'neutral',
                                       'evidence_ids': ['d_40'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '這段期間的成交量普遍比近五日平均少三成到六成，市場對這檔股票的關注度非常低。',
                                       'direction': 'negative',
                                       'evidence_ids': ['d_33', 'd_35', 'd_37'],
                                       'importance': 'high'}],
                   'positive_factors': [{'id': 'pos_01',
                                         'claim_type': 'observation',
                                         'text': '三月二十日外資單日買超超過三萬四千張，是這四十個交易日裡外資最大的一筆買超。',
                                         'direction': 'positive',
                                         'evidence_ids': ['d_40'],
                                         'importance': 'high'},
                                        {'id': 'pos_02',
                                         'claim_type': 'observation',
                                         'text': '估值處在相對低的位置，本益比只有七倍出頭、股價淨值比不到一倍，向下的評價緩衝比多數個股明顯。',
                                         'direction': 'positive',
                                         'evidence_ids': ['fd_05', 'fd_06'],
                                         'importance': 'medium'}],
                   'negative_factors': [{'id': 'neg_01',
                                         'claim_type': 'observation',
                                         'text': '二月營收 105.8 億元，比上個月少了一成六，年增率也只回到零附近，前面半年多都是年衰退。',
                                         'direction': 'negative',
                                         'evidence_ids': ['fd_04'],
                                         'importance': 'high'},
                                        {'id': 'neg_02',
                                         'claim_type': 'inference',
                                         'text': '上行動能在這兩週由正轉負，加上持續萎縮的成交量，代表反彈缺乏後續買盤支持。',
                                         'direction': 'negative',
                                         'evidence_ids': ['d_31', 'd_39', 'd_40'],
                                         'importance': 'high'},
                                        {'id': 'neg_03',
                                         'claim_type': 'observation',
                                         'text': '股價落在近一年高低區間偏低的位置，距離一年前的高點還有相當大的距離。',
                                         'direction': 'negative',
                                         'evidence_ids': ['lt_01', 'lt_03'],
                                         'importance': 'medium'}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '同一天外資大買、投信大賣，規模幾乎相等，兩大法人對這檔股票的看法完全相反。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['d_40'],
                                           'importance': 'high'},
                                          {'id': 'div_02',
                                           'claim_type': 'limitation',
                                           'text': '這四十個交易日沒有檢索到任何有效期間內的新聞，無法用消息面驗證法人行為的動機。',
                                           'direction': 'not_applicable',
                                           'evidence_ids': [],
                                           'importance': 'medium'}],
                   'risks': [{'id': 'rk_01',
                              'risk_type': '籌碼',
                              'description': '三月二十日的外資買超與投信賣超規模相當，如果隔天沒有延續，很可能只是單日換手而不是趨勢轉變。',
                              'trigger': '外資買超在下一個交易日就中斷',
                              'evidence_ids': ['d_40']},
                             {'id': 'rk_02',
                              'risk_type': '營運',
                              'description': '月營收年增率剛從兩位數衰退回到零附近，但還沒有轉正，營運改善的力道尚未被證實。',
                              'trigger': '三月營收年增率再度轉為負值',
                              'evidence_ids': ['fd_04']},
                             {'id': 'rk_03',
                              'risk_type': '流動性',
                              'description': '多數交易日的成交量不到近五日平均的一半，這種量能下任何較大的單子都容易造成明顯波動。',
                              'trigger': '單日成交量再度縮到近五日平均的四成以下',
                              'evidence_ids': ['d_35', 'd_37']}],
                   'watch_points': [{'id': 'wp_01',
                                     'what_to_watch': '外資的買超有沒有連續',
                                     'why_it_matters': '三月二十日的大額買超是這段期間唯一的異常訊號，能不能連續兩三天，決定它是單純換手還是資金真的回頭。',
                                     'when': '接下來三個交易日的法人資料',
                                     'evidence_ids': ['d_40']},
                                    {'id': 'wp_02',
                                     'what_to_watch': '三月營收公告',
                                     'why_it_matters': '二月營收年增率剛回到零附近，三月能不能真正轉正，是判斷營運觸底的第一個客觀指標。',
                                     'when': '四月十日前',
                                     'evidence_ids': ['fd_04']},
                                    {'id': 'wp_03',
                                     'what_to_watch': '上漲時成交量有沒有跟上',
                                     'why_it_matters': '這段期間上漲幾乎都是量縮，只有出現量價同步放大的日子，才代表買方態度真的改變。',
                                     'when': '接下來的每個交易日',
                                     'evidence_ids': ['d_31', 'd_40']},
                                    {'id': 'wp_04',
                                     'what_to_watch': '上一年度第四季財報',
                                     'why_it_matters': '目前能取得的正式財報只到第三季，第四季數字出來才能確認獲利是延續回升還是再度轉弱。',
                                     'when': '三月底前',
                                     'evidence_ids': ['fd_01']}],
                   'forward_views': {'short_1_5': {'stance': 'neutral',
                                                   'reason': '價格貼著近一個月平均、成交量長期偏低，缺乏推動任何一個方向的力量。',
                                                   'invalidation': '連續兩天出現量價同步放大，或外資買超轉為連續',
                                                   'evidence_ids': ['d_40', 'd_35']},
                                     'swing_6_20': {'stance': 'uncertain',
                                                    'reason': '外資與投信在最後一天做出完全相反的動作，方向要等法人態度分出高下才看得出來。',
                                                    'invalidation': '其中一方連續三天維持同一方向',
                                                    'evidence_ids': ['d_40']},
                                     'medium_21_40': {'stance': 'mildly_bearish',
                                                      'reason': '營收還在年衰退與零成長之間、獲利尚未確認回升，中期的基本面支持仍然不足。',
                                                      'invalidation': '單月營收年增率連續兩期轉正',
                                                      'evidence_ids': ['fd_04', 'fd_01']}},
                   'overall_stance': 'uncertain',
                   'confidence': 'low',
                   'confidence_reason': '價量與籌碼資料完整，但整段期間沒有可用新聞，正式財報也只到上一季，關鍵資訊缺口偏大。',
                   'limitations': ['四十個交易日內沒有檢索到有效期間的新聞，無法判斷法人行為背後的消息面原因。',
                                   '最新一期正式財報為 2025 年第三季，第四季財報尚未公告，最近的獲利狀況無法確認。',
                                   '多數交易日成交量偏低，單日的價量訊號雜訊較高。']}},
 {'scenario': '新聞偏多但市場資料未確認',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2408',
                             'as_of_date': '2026-04-24',
                             'timeline_trading_days': 40,
                             'analysis_language': 'zh-TW'},
                    'daily_timeline': [{'id': 'd_29',
                                        'date': '2026-04-09',
                                        'close': 205.0,
                                        'chg_pct': -8.07,
                                        'vol_lots': 90701,
                                        'vol_vs_ma5_pct': -9.0,
                                        'foreign_net_lots': -33225,
                                        'trust_net_lots': -790,
                                        'dealer_net_lots': -990,
                                        'rsi5': 40.9,
                                        'kd_k': 20.9,
                                        'macd_hist': -1.51,
                                        'vs_ma20_pct': -11.1,
                                        'news': []},
                                       {'id': 'd_30',
                                        'date': '2026-04-10',
                                        'close': 215.0,
                                        'chg_pct': 4.88,
                                        'vol_lots': 93634,
                                        'vol_vs_ma5_pct': -1.0,
                                        'foreign_net_lots': 18152,
                                        'trust_net_lots': -262,
                                        'dealer_net_lots': 1102,
                                        'rsi5': 50.7,
                                        'kd_k': 33.2,
                                        'macd_hist': -0.62,
                                        'vs_ma20_pct': -5.9,
                                        'news': ['nw_01']},
                                       {'id': 'd_31',
                                        'date': '2026-04-13',
                                        'close': 225.5,
                                        'chg_pct': 4.88,
                                        'vol_lots': 97514,
                                        'vol_vs_ma5_pct': 8.0,
                                        'foreign_net_lots': 8798,
                                        'trust_net_lots': -181,
                                        'dealer_net_lots': 2373,
                                        'rsi5': 59.5,
                                        'kd_k': 53.2,
                                        'macd_hist': 0.74,
                                        'vs_ma20_pct': -1.0,
                                        'news': ['nw_03']},
                                       {'id': 'd_32',
                                        'date': '2026-04-14',
                                        'close': 220.0,
                                        'chg_pct': -2.44,
                                        'vol_lots': 161561,
                                        'vol_vs_ma5_pct': 50.0,
                                        'foreign_net_lots': -41591,
                                        'trust_net_lots': 120,
                                        'dealer_net_lots': -2857,
                                        'rsi5': 53.3,
                                        'kd_k': 52.7,
                                        'macd_hist': 1.31,
                                        'vs_ma20_pct': -3.1,
                                        'news': []},
                                       {'id': 'd_33',
                                        'date': '2026-04-15',
                                        'close': 211.5,
                                        'chg_pct': -3.86,
                                        'vol_lots': 106926,
                                        'vol_vs_ma5_pct': -3.0,
                                        'foreign_net_lots': -755,
                                        'trust_net_lots': -2479,
                                        'dealer_net_lots': -3093,
                                        'rsi5': 44.3,
                                        'kd_k': 44.7,
                                        'macd_hist': 1.16,
                                        'vs_ma20_pct': -5.8,
                                        'news': []},
                                       {'id': 'd_34',
                                        'date': '2026-04-16',
                                        'close': 213.5,
                                        'chg_pct': 0.95,
                                        'vol_lots': 52963,
                                        'vol_vs_ma5_pct': -48.0,
                                        'foreign_net_lots': 8634,
                                        'trust_net_lots': -3801,
                                        'dealer_net_lots': 158,
                                        'rsi5': 46.9,
                                        'kd_k': 41.1,
                                        'macd_hist': 1.22,
                                        'vs_ma20_pct': -3.6,
                                        'news': []},
                                       {'id': 'd_35',
                                        'date': '2026-04-17',
                                        'close': 210.0,
                                        'chg_pct': -1.64,
                                        'vol_lots': 68275,
                                        'vol_vs_ma5_pct': -30.0,
                                        'foreign_net_lots': -1760,
                                        'trust_net_lots': -2362,
                                        'dealer_net_lots': -215,
                                        'rsi5': 42.5,
                                        'kd_k': 34.0,
                                        'macd_hist': 1.07,
                                        'vs_ma20_pct': -3.8,
                                        'news': []},
                                       {'id': 'd_36',
                                        'date': '2026-04-20',
                                        'close': 207.0,
                                        'chg_pct': -1.43,
                                        'vol_lots': 68204,
                                        'vol_vs_ma5_pct': -26.0,
                                        'foreign_net_lots': 9127,
                                        'trust_net_lots': 111,
                                        'dealer_net_lots': -587,
                                        'rsi5': 38.7,
                                        'kd_k': 27.1,
                                        'macd_hist': 0.82,
                                        'vs_ma20_pct': -4.0,
                                        'news': []},
                                       {'id': 'd_37',
                                        'date': '2026-04-21',
                                        'close': 220.0,
                                        'chg_pct': 6.28,
                                        'vol_lots': 109826,
                                        'vol_vs_ma5_pct': 35.0,
                                        'foreign_net_lots': 6591,
                                        'trust_net_lots': 652,
                                        'dealer_net_lots': 567,
                                        'rsi5': 58.9,
                                        'kd_k': 33.9,
                                        'macd_hist': 1.53,
                                        'vs_ma20_pct': 2.4,
                                        'news': []},
                                       {'id': 'd_38',
                                        'date': '2026-04-22',
                                        'close': 219.0,
                                        'chg_pct': -0.45,
                                        'vol_lots': 71111,
                                        'vol_vs_ma5_pct': -4.0,
                                        'foreign_net_lots': 1998,
                                        'trust_net_lots': 62,
                                        'dealer_net_lots': -115,
                                        'rsi5': 57.1,
                                        'kd_k': 37.5,
                                        'macd_hist': 1.93,
                                        'vs_ma20_pct': 2.0,
                                        'news': []},
                                       {'id': 'd_39',
                                        'date': '2026-04-23',
                                        'close': 208.0,
                                        'chg_pct': -5.02,
                                        'vol_lots': 141104,
                                        'vol_vs_ma5_pct': 54.0,
                                        'foreign_net_lots': -17424,
                                        'trust_net_lots': -1331,
                                        'dealer_net_lots': -22,
                                        'rsi5': 40.1,
                                        'kd_k': 30.2,
                                        'macd_hist': 1.45,
                                        'vs_ma20_pct': -2.9,
                                        'news': []},
                                       {'id': 'd_40',
                                        'date': '2026-04-24',
                                        'close': 206.0,
                                        'chg_pct': -0.96,
                                        'vol_lots': 99651,
                                        'vol_vs_ma5_pct': 2.0,
                                        'foreign_net_lots': -13361,
                                        'trust_net_lots': -1374,
                                        'dealer_net_lots': -32,
                                        'rsi5': 37.6,
                                        'kd_k': 25.9,
                                        'macd_hist': 1.02,
                                        'vs_ma20_pct': -3.4,
                                        'news': []}],
                    'long_term_anchor': [{'id': 'lt_01',
                                          'field': 'high_1y',
                                          'date': '2026-01-30',
                                          'value': 326.5},
                                         {'id': 'lt_02',
                                          'field': 'low_1y',
                                          'date': '2025-05-05',
                                          'value': 34.25},
                                         {'id': 'lt_03',
                                          'field': 'close_pos_in_1y_pct',
                                          'date': '2026-04-24',
                                          'value': 58.8},
                                         {'id': 'lt_04',
                                          'field': 'vs_ma60_pct',
                                          'date': '2026-04-24',
                                          'value': -16.9},
                                         {'id': 'lt_05',
                                          'field': 'vs_ma240_pct',
                                          'date': '2026-04-24',
                                          'value': 57.0}],
                    'fundamental': [{'id': 'fd_01',
                                     'field': 'eps',
                                     'period': '2025Q4',
                                     'date': '2025-12-31',
                                     'value': 3.58,
                                     'qoq_pct': 616.0,
                                     'last4q': [['2025Q1', -0.63],
                                                ['2025Q2', -1.32],
                                                ['2025Q3', 0.5],
                                                ['2025Q4', 3.58]]},
                                    {'id': 'fd_02',
                                     'field': 'gross_margin_pct',
                                     'period': '2025Q4',
                                     'date': '2025-12-31',
                                     'value': 49.0},
                                    {'id': 'fd_03',
                                     'field': 'operating_margin_pct',
                                     'period': '2025Q4',
                                     'date': '2025-12-31',
                                     'value': 39.1},
                                    {'id': 'fd_04',
                                     'field': 'revenue_monthly',
                                     'period': '2026-03',
                                     'value': 18169760000,
                                     'yoy_pct': 560.0,
                                     'mom_pct': 16.4,
                                     'yoy_last6': [['2025-10', 262.4],
                                                   ['2025-11', 364.9],
                                                   ['2025-12', 444.9],
                                                   ['2026-01', 608.0],
                                                   ['2026-02', 586.7],
                                                   ['2026-03', 560.0]]},
                                    {'id': 'fd_05',
                                     'field': 'revenue_yoy_positive_streak',
                                     'period': '2026-03',
                                     'value': 10},
                                    {'id': 'fd_06',
                                     'field': 'per',
                                     'date': '2026-04-24',
                                     'value': 96.71,
                                     'pct_rank_1y': 87},
                                    {'id': 'fd_07',
                                     'field': 'pbr',
                                     'date': '2026-04-24',
                                     'value': 3.75,
                                     'pct_rank_1y': 72},
                                    {'id': 'fd_08',
                                     'field': 'dividend_yield',
                                     'date': '2026-04-24',
                                     'value': 0.73,
                                     'pct_rank_1y': 99}],
                    'news': [{'id': 'nw_01',
                              'field': 'news',
                              'date': '2026-04-10',
                              'kind': 'general',
                              'title': '〈台塑四寶業績〉中東戰爭引爆塑化報價 四寶3月營收年月雙增、台塑化Q1獲利最佳',
                              'value': '南亞各產品中，電子材料營收占比達 5 成以上，營運狀況最佳，加上 AI '
                                       '市場規模持續擴張、中高階材料供應緊缺，連帶使一般…'},
                             {'id': 'nw_02',
                              'field': 'news',
                              'date': '2026-03-26',
                              'kind': 'general',
                              'title': '焦點股》南亞科引進大咖入股 台勝科、福懋科股價歡慶',
                              'value': '南亞科引進大咖入股，台勝科、福懋科股價歡慶。（圖取自官網） '
                                       'DRAM廠南亞科（2408）辦理私募增資，挾DDR4受惠AI…'},
                             {'id': 'nw_03',
                              'field': 'news',
                              'date': '2026-04-13',
                              'kind': 'general',
                              'title': '〈南亞科法說〉Q1雙率飆破6成 每股大賺8.41元創新高',
                              'value': '南亞科 (2408-TW) 今 (13) 日舉行法說會，並公布第一季財報，儘管出貨受傳統淡季影響呈現略減，但在第一季 '
                                       'D…'}],
                    'missing_fields': []},
  'output_brief': {'key_days': [{'id': 'kd_01',
                                 'date': '2026-04-13',
                                 'ref': 'd_31',
                                 'what': '法說會公布上一季獲利創新高當天，股價上漲 4.88%，但成交量只比近五日平均多 '
                                         '8%，外資雖然買超近八千八百張，追價力道並不明顯。',
                                 'evidence_ids': ['d_31', 'nw_03']},
                                {'id': 'kd_02',
                                 'date': '2026-04-14',
                                 'ref': 'd_32',
                                 'what': '好消息隔天反而下跌 2.44%，成交量放大 50%，外資單日倒出超過四萬一千張，前一天的樂觀情緒完全沒有延續。',
                                 'evidence_ids': ['d_32']},
                                {'id': 'kd_03',
                                 'date': '2026-04-21',
                                 'ref': 'd_37',
                                 'what': '股價單日彈升 6.28%，成交量增加 35%，但三大法人買超規模都不大，這波反彈缺乏籌碼實質支持。',
                                 'evidence_ids': ['d_37']},
                                {'id': 'kd_04',
                                 'date': '2026-04-23',
                                 'ref': 'd_39',
                                 'what': '再度重挫 5.02%，成交量放大 54%，外資又賣超一萬七千多張，兩天前的反彈全部被吃回去。',
                                 'evidence_ids': ['d_39']}],
                   'headline': '財報大好但股價回不去，法人反覆調節、量能只在下跌時放大',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '四月二十四日收在 206 '
                                               '元，已經連續幾天落在近一個月的平均價位之下，而且這段期間只要上漲成交量就縮、下跌成交量就放大。',
                                       'direction': 'negative',
                                       'evidence_ids': ['d_40', 'd_39'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '以近一年來看股價還在區間偏上方的位置，但已經比近三個月的平均價位低了一成七，中期走勢明顯轉弱。',
                                       'direction': 'mixed',
                                       'evidence_ids': ['lt_03', 'lt_04'],
                                       'importance': 'medium'}],
                   'positive_factors': [{'id': 'pos_01',
                                         'claim_type': 'inference',
                                         'text': '上一季每股純益回到 3.58 元，結束前面連續兩季的虧損，獲利結構確實在好轉。',
                                         'direction': 'positive',
                                         'evidence_ids': ['fd_01'],
                                         'importance': 'high'},
                                        {'id': 'pos_02',
                                         'claim_type': 'observation',
                                         'text': '三月營收 181.7 億元，比去年同期成長 5.6 倍，而且年成長已經連續維持十個月。',
                                         'direction': 'positive',
                                         'evidence_ids': ['fd_04', 'fd_05'],
                                         'importance': 'high'},
                                        {'id': 'pos_03',
                                         'claim_type': 'observation',
                                         'text': '四月二十一日單日彈升超過六個百分點，顯示只要有題材，買方仍然願意回頭承接。',
                                         'direction': 'positive',
                                         'evidence_ids': ['d_37'],
                                         'importance': 'medium'}],
                   'negative_factors': [{'id': 'neg_01',
                                         'claim_type': 'inference',
                                         'text': '外資在四月十四日與二十三日兩度大量調節，合計倒出將近六萬張，法說會的利多沒有轉化成持續的買盤。',
                                         'direction': 'negative',
                                         'evidence_ids': ['d_32', 'd_39', 'nw_03'],
                                         'importance': 'high'},
                                        {'id': 'neg_02',
                                         'claim_type': 'observation',
                                         'text': '量能結構並不健康：上漲的日子成交量只增加個位數到三成多，下跌的日子卻放大五成以上，賣方比買方積極。',
                                         'direction': 'negative',
                                         'evidence_ids': ['d_31', 'd_37', 'd_32', 'd_39'],
                                         'importance': 'high'},
                                        {'id': 'neg_03',
                                         'claim_type': 'inference',
                                         'text': '本益比接近百倍，股價已經反映了相當高的獲利成長預期，一旦成長速度不如預期，回檔幅度容易被放大。',
                                         'direction': 'negative',
                                         'evidence_ids': ['fd_06'],
                                         'importance': 'medium'}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '媒體報導的是獲利創新高的好消息，但同一段期間股價與法人動向都往反方向走，兩者明顯背離。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['nw_03', 'd_32', 'd_39'],
                                           'importance': 'high'},
                                          {'id': 'div_02',
                                           'claim_type': 'conflict',
                                           'text': '正式財報顯示上一季每股純益 3.58 元，媒體則已報導最新一季賺 8.41 '
                                                   '元，後者尚未進入正式財報，兩個數字不能混用。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['fd_01', 'nw_03'],
                                           'importance': 'medium'}],
                   'risks': [{'id': 'rk_01',
                              'risk_type': '籌碼',
                              'description': '外資近兩週整體是淨賣超，而且賣壓集中在下跌日，這個節奏若延續，反彈都容易被壓回。',
                              'trigger': '外資單日賣超再度超過一萬張，且股價同步收黑',
                              'evidence_ids': ['d_32', 'd_39', 'd_40']},
                             {'id': 'rk_02',
                              'risk_type': '評價',
                              'description': '本益比接近百倍，遠高於獲利穩定期的常見水準，估值對任何消息都會非常敏感。',
                              'trigger': '後續單月營收年增率明顯放緩',
                              'evidence_ids': ['fd_06', 'fd_04']},
                             {'id': 'rk_03',
                              'risk_type': '產業',
                              'description': '記憶體報價是這波獲利跳升的主因，價格循環一旦反轉，獲利下修的速度也會很快。',
                              'trigger': '單月營收由年成長轉為年衰退',
                              'evidence_ids': ['fd_04', 'fd_05']}],
                   'watch_points': [{'id': 'wp_01',
                                     'what_to_watch': '四月營收公告',
                                     'why_it_matters': '三月營收年增 5.6 '
                                                       '倍是這波股價的核心依據，四月能否維持同樣力道，是驗證獲利動能有沒有續航的第一個關卡。',
                                     'when': '五月十日前',
                                     'evidence_ids': ['fd_04', 'fd_05']},
                                    {'id': 'wp_02',
                                     'what_to_watch': '外資的連續調節有沒有停下來',
                                     'why_it_matters': '近兩週的下跌都伴隨外資大量賣超，只要這股賣壓沒有停，反彈就很難站穩。',
                                     'when': '接下來一到兩週的每日法人資料',
                                     'evidence_ids': ['d_32', 'd_39']},
                                    {'id': 'wp_03',
                                     'what_to_watch': '正式季報的每股純益數字',
                                     'why_it_matters': '正式財報目前只到上一季的 3.58 元，媒體報導的 8.41 '
                                                       '元還沒落進財報資料，正式數字出來才能確認獲利跳升的幅度。',
                                     'when': '五月中旬季報公告',
                                     'evidence_ids': ['fd_01', 'nw_03']},
                                    {'id': 'wp_04',
                                     'what_to_watch': '上漲日的成交量能不能放大',
                                     'why_it_matters': '這段期間上漲都是量縮、下跌才放量，只有出現量價同步放大的日子，才代表買方態度真的轉變。',
                                     'when': '接下來的每個交易日',
                                     'evidence_ids': ['d_31', 'd_37', 'd_39']}],
                   'forward_views': {'short_1_5': {'stance': 'mildly_bearish',
                                                   'reason': '最近兩天都收在近一個月的平均價位下方，量能又只在下跌時放大，短線賣壓還沒消化完。',
                                                   'invalidation': '出現量價同步放大、且三大法人同步偏買超的交易日',
                                                   'evidence_ids': ['d_39', 'd_40']},
                                     'swing_6_20': {'stance': 'mixed',
                                                    'reason': '獲利與營收成長是實在的，但外資持續調節、估值又偏高，兩股力量互相拉扯。',
                                                    'invalidation': '外資轉為連續買超，或單月營收成長明顯降速',
                                                    'evidence_ids': ['fd_01',
                                                                     'fd_04',
                                                                     'd_32',
                                                                     'd_39']},
                                     'medium_21_40': {'stance': 'uncertain',
                                                      'reason': '中期方向取決於記憶體價格循環還能撐多久，現有資料看不到足以定調的依據。',
                                                      'invalidation': '季報與月營收出現連續兩期的成長轉折',
                                                      'evidence_ids': ['fd_04', 'fd_05', 'lt_04']}},
                   'overall_stance': 'mixed',
                   'confidence': 'medium',
                   'confidence_reason': '價量、籌碼與基本面資料都齊全，但基本面明顯偏多、價量與籌碼明顯偏空，方向互相矛盾，因此只能給中等信心。',
                   'limitations': ['媒體報導的最新一季獲利數字尚未出現在正式財報資料中，只能當作展望參考。',
                                   '檢索到的三則新聞中有一則是集團整體業績報導，與本檔個股的關聯性有限。']}},
 {'scenario': '基本面強但籌碼與量能偏弱',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2330',
                             'as_of_date': '2026-07-13',
                             'timeline_trading_days': 40,
                             'analysis_language': 'zh-TW'},
                    'daily_timeline': [{'id': 'd_29',
                                        'date': '2026-06-25',
                                        'close': 2390.0,
                                        'chg_pct': 0.0,
                                        'vol_lots': 41100,
                                        'vol_vs_ma5_pct': -15.0,
                                        'foreign_net_lots': -6104,
                                        'trust_net_lots': 179,
                                        'dealer_net_lots': -310,
                                        'rsi5': 46.4,
                                        'kd_k': 64.4,
                                        'macd_hist': 0.76,
                                        'vs_ma20_pct': 1.0,
                                        'news': []},
                                       {'id': 'd_30',
                                        'date': '2026-06-26',
                                        'close': 2340.0,
                                        'chg_pct': -2.09,
                                        'vol_lots': 53800,
                                        'vol_vs_ma5_pct': 9.0,
                                        'foreign_net_lots': -14281,
                                        'trust_net_lots': 734,
                                        'dealer_net_lots': 1009,
                                        'rsi5': 35.8,
                                        'kd_k': 45.3,
                                        'macd_hist': -5.58,
                                        'vs_ma20_pct': -1.2,
                                        'news': []},
                                       {'id': 'd_31',
                                        'date': '2026-06-29',
                                        'close': 2370.0,
                                        'chg_pct': 1.28,
                                        'vol_lots': 38134,
                                        'vol_vs_ma5_pct': -21.0,
                                        'foreign_net_lots': -1912,
                                        'trust_net_lots': 919,
                                        'dealer_net_lots': 997,
                                        'rsi5': 45.2,
                                        'kd_k': 37.4,
                                        'macd_hist': -7.77,
                                        'vs_ma20_pct': 0.0,
                                        'news': []},
                                       {'id': 'd_32',
                                        'date': '2026-06-30',
                                        'close': 2410.0,
                                        'chg_pct': 1.69,
                                        'vol_lots': 49540,
                                        'vol_vs_ma5_pct': -1.0,
                                        'foreign_net_lots': -1426,
                                        'trust_net_lots': -90,
                                        'dealer_net_lots': 652,
                                        'rsi5': 56.0,
                                        'kd_k': 38.4,
                                        'macd_hist': -6.6,
                                        'vs_ma20_pct': 1.6,
                                        'news': []},
                                       {'id': 'd_33',
                                        'date': '2026-07-01',
                                        'close': 2505.0,
                                        'chg_pct': 3.94,
                                        'vol_lots': 37544,
                                        'vol_vs_ma5_pct': -15.0,
                                        'foreign_net_lots': 7400,
                                        'trust_net_lots': 4743,
                                        'dealer_net_lots': -386,
                                        'rsi5': 72.2,
                                        'kd_k': 54.2,
                                        'macd_hist': 0.15,
                                        'vs_ma20_pct': 5.3,
                                        'news': ['nw_02', 'nw_03', 'nw_04']},
                                       {'id': 'd_34',
                                        'date': '2026-07-02',
                                        'close': 2465.0,
                                        'chg_pct': -1.6,
                                        'vol_lots': 35919,
                                        'vol_vs_ma5_pct': -16.0,
                                        'foreign_net_lots': -12254,
                                        'trust_net_lots': 1026,
                                        'dealer_net_lots': 217,
                                        'rsi5': 60.5,
                                        'kd_k': 58.3,
                                        'macd_hist': 1.42,
                                        'vs_ma20_pct': 3.6,
                                        'news': ['nw_01']},
                                       {'id': 'd_35',
                                        'date': '2026-07-03',
                                        'close': 2445.0,
                                        'chg_pct': -0.81,
                                        'vol_lots': 32906,
                                        'vol_vs_ma5_pct': -15.0,
                                        'foreign_net_lots': -12537,
                                        'trust_net_lots': 821,
                                        'dealer_net_lots': 653,
                                        'rsi5': 54.9,
                                        'kd_k': 57.9,
                                        'macd_hist': 0.47,
                                        'vs_ma20_pct': 2.6,
                                        'news': []},
                                       {'id': 'd_36',
                                        'date': '2026-07-06',
                                        'close': 2460.0,
                                        'chg_pct': 0.61,
                                        'vol_lots': 21042,
                                        'vol_vs_ma5_pct': -41.0,
                                        'foreign_net_lots': -241,
                                        'trust_net_lots': 380,
                                        'dealer_net_lots': 119,
                                        'rsi5': 58.5,
                                        'kd_k': 63.6,
                                        'macd_hist': 0.4,
                                        'vs_ma20_pct': 3.0,
                                        'news': []},
                                       {'id': 'd_37',
                                        'date': '2026-07-07',
                                        'close': 2440.0,
                                        'chg_pct': -0.81,
                                        'vol_lots': 31401,
                                        'vol_vs_ma5_pct': -1.0,
                                        'foreign_net_lots': 83,
                                        'trust_net_lots': 539,
                                        'dealer_net_lots': -237,
                                        'rsi5': 51.6,
                                        'kd_k': 63.7,
                                        'macd_hist': -1.34,
                                        'vs_ma20_pct': 1.9,
                                        'news': []},
                                       {'id': 'd_38',
                                        'date': '2026-07-08',
                                        'close': 2465.0,
                                        'chg_pct': 1.02,
                                        'vol_lots': 25520,
                                        'vol_vs_ma5_pct': -13.0,
                                        'foreign_net_lots': -4155,
                                        'trust_net_lots': 730,
                                        'dealer_net_lots': 468,
                                        'rsi5': 59.1,
                                        'kd_k': 68.4,
                                        'macd_hist': -1.17,
                                        'vs_ma20_pct': 2.6,
                                        'news': []},
                                       {'id': 'd_39',
                                        'date': '2026-07-09',
                                        'close': 2415.0,
                                        'chg_pct': -2.03,
                                        'vol_lots': 34681,
                                        'vol_vs_ma5_pct': 19.0,
                                        'foreign_net_lots': -12749,
                                        'trust_net_lots': 43,
                                        'dealer_net_lots': 90,
                                        'rsi5': 42.6,
                                        'kd_k': 61.8,
                                        'macd_hist': -4.59,
                                        'vs_ma20_pct': 0.2,
                                        'news': ['nw_05']},
                                       {'id': 'd_40',
                                        'date': '2026-07-13',
                                        'close': 2440.0,
                                        'chg_pct': 1.04,
                                        'vol_lots': 35310,
                                        'vol_vs_ma5_pct': 19.0,
                                        'foreign_net_lots': -2045,
                                        'trust_net_lots': 530,
                                        'dealer_net_lots': 623,
                                        'rsi5': 51.1,
                                        'kd_k': 51.7,
                                        'macd_hist': -5.28,
                                        'vs_ma20_pct': 0.8,
                                        'news': []}],
                    'long_term_anchor': [{'id': 'lt_01',
                                          'field': 'high_1y',
                                          'date': '2026-06-22',
                                          'value': 2510.0},
                                         {'id': 'lt_02',
                                          'field': 'low_1y',
                                          'date': '2025-07-14',
                                          'value': 1095.0},
                                         {'id': 'lt_03',
                                          'field': 'close_pos_in_1y_pct',
                                          'date': '2026-07-13',
                                          'value': 95.1},
                                         {'id': 'lt_04',
                                          'field': 'vs_ma60_pct',
                                          'date': '2026-07-13',
                                          'value': 6.1},
                                         {'id': 'lt_05',
                                          'field': 'vs_ma240_pct',
                                          'date': '2026-07-13',
                                          'value': 42.9}],
                    'fundamental': [{'id': 'fd_01',
                                     'field': 'eps',
                                     'period': '2026Q1',
                                     'date': '2026-03-31',
                                     'value': 22.08,
                                     'qoq_pct': 13.2,
                                     'yoy_pct': 58.3,
                                     'last4q': [['2025Q2', 15.36],
                                                ['2025Q3', 17.44],
                                                ['2025Q4', 19.51],
                                                ['2026Q1', 22.08]]},
                                    {'id': 'fd_02',
                                     'field': 'gross_margin_pct',
                                     'period': '2026Q1',
                                     'date': '2026-03-31',
                                     'value': 66.2},
                                    {'id': 'fd_03',
                                     'field': 'operating_margin_pct',
                                     'period': '2026Q1',
                                     'date': '2026-03-31',
                                     'value': 58.1},
                                    {'id': 'fd_04',
                                     'field': 'revenue_monthly',
                                     'period': '2026-06',
                                     'value': 442679969000,
                                     'yoy_pct': 67.9,
                                     'mom_pct': 6.2,
                                     'yoy_last6': [['2026-01', 36.8],
                                                   ['2026-02', 22.2],
                                                   ['2026-03', 45.2],
                                                   ['2026-04', 17.5],
                                                   ['2026-05', 30.1],
                                                   ['2026-06', 67.9]]},
                                    {'id': 'fd_05',
                                     'field': 'revenue_yoy_positive_streak',
                                     'period': '2026-06',
                                     'value': 14},
                                    {'id': 'fd_06',
                                     'field': 'per',
                                     'date': '2026-07-13',
                                     'value': 32.8,
                                     'pct_rank_1y': 91},
                                    {'id': 'fd_07',
                                     'field': 'pbr',
                                     'date': '2026-07-13',
                                     'value': 10.74,
                                     'pct_rank_1y': 94},
                                    {'id': 'fd_08',
                                     'field': 'dividend_yield',
                                     'date': '2026-07-13',
                                     'value': 0.9,
                                     'pct_rank_1y': 5}],
                    'news': [{'id': 'nw_01',
                              'field': 'news',
                              'date': '2026-07-02',
                              'kind': 'general',
                              'title': '〈台股開盤〉逾千跌點回測4萬6後跌幅收斂 機器人、無人機聯歡齊嗨',
                              'value': '美股今日凌晨收盤部分，道瓊下跌 13.96 點或 0.03%，收報 52,305.24 點；標普 500 下跌 '
                                       '16.1…'},
                             {'id': 'nw_02',
                              'field': 'news',
                              'date': '2026-07-01',
                              'kind': 'general',
                              'title': '盤中速報 - 集中市場加權指數上漲946.67點至47072.58點，漲幅2.05%',
                              'value': '截至台北時間01日11:29，集中市場加權指數上漲946.67點（或2.05%），暫報47072.58點。 '
                                       '歷史漲跌幅 …'},
                             {'id': 'nw_03',
                              'field': 'news',
                              'date': '2026-07-01',
                              'kind': 'general',
                              'title': '盤中速報 - 集中市場加權指數上漲925.03點至47050.94點，漲幅2.01%',
                              'value': '截至台北時間01日11:36，集中市場加權指數上漲925.03點（或2.01%），暫報47050.94點。 '
                                       '歷史漲跌幅 …'},
                             {'id': 'nw_04',
                              'field': 'news',
                              'date': '2026-07-01',
                              'kind': 'general',
                              'title': '盤中速報 - 集中市場加權指數上漲934.47點至47060.38點，漲幅2.03%',
                              'value': '截至台北時間01日11:47，集中市場加權指數上漲934.47點（或2.03%），暫報47060.38點。 '
                                       '歷史漲跌幅 …'},
                             {'id': 'nw_05',
                              'field': 'news',
                              'date': '2026-07-09',
                              'kind': 'general',
                              'title': '外資賣超471億元連6賣 光是台積電就提款310億元',
                              'value': '資深證券分析師簡伯儀指出，台股集中市場近期出現量能萎縮格局，而在大型颱風巴威逼近同時，更使得買盤縮手，甚至買了也不敢貿然…'}],
                    'missing_fields': []},
  'output_brief': {'key_days': [{'id': 'kd_01',
                                 'date': '2026-07-01',
                                 'ref': 'd_33',
                                 'what': '單日大漲 3.94%，外資與投信同步買超，但成交量反而比近五日平均少 15%，這波上漲是在量縮的情況下發生的。',
                                 'evidence_ids': ['d_33']},
                                {'id': 'kd_02',
                                 'date': '2026-07-02',
                                 'ref': 'd_34',
                                 'what': '隔天回檔 1.6%，外資單日倒出一萬兩千多張，前一天的買超立刻被抵銷掉。',
                                 'evidence_ids': ['d_34']},
                                {'id': 'kd_03',
                                 'date': '2026-07-09',
                                 'ref': 'd_39',
                                 'what': '下跌 2.03%，成交量放大 '
                                         '19%，外資又賣超近一萬三千張，當天新聞也提到外資對這檔股票的大額調節，兩邊互相印證。',
                                 'evidence_ids': ['d_39', 'nw_05']},
                                {'id': 'kd_04',
                                 'date': '2026-07-13',
                                 'ref': 'd_40',
                                 'what': '小幅反彈 1.04%，成交量同樣放大 19%，但外資仍然是賣超、投信買超規模不大，反彈的籌碼基礎並不厚。',
                                 'evidence_ids': ['d_40']}],
                   'headline': '獲利與營收成長強勁，但股價原地整理、外資持續調節',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '七月十三日收在 2440 元，只比近一個月的平均價位高不到一個百分點，最近兩週幾乎是原地整理。',
                                       'direction': 'neutral',
                                       'evidence_ids': ['d_40'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '股價位置很高，落在近一年區間的九成五附近，但上行動能已經連續多日轉為負值而且持續擴大。',
                                       'direction': 'mixed',
                                       'evidence_ids': ['lt_03', 'd_40'],
                                       'importance': 'high'},
                                      {'id': 'cs_03',
                                       'claim_type': 'observation',
                                       'text': '這段期間大多數交易日的成交量都低於近五日平均，只有下跌的日子量能才明顯放大。',
                                       'direction': 'negative',
                                       'evidence_ids': ['d_33', 'd_39'],
                                       'importance': 'medium'}],
                   'positive_factors': [{'id': 'pos_01',
                                         'claim_type': 'observation',
                                         'text': '最近一季每股純益 22.08 元，比去年同期成長將近六成，而且已經連續四季逐季走高。',
                                         'direction': 'positive',
                                         'evidence_ids': ['fd_01'],
                                         'importance': 'high'},
                                        {'id': 'pos_02',
                                         'claim_type': 'observation',
                                         'text': '六月營收 4427 億元，年增將近七成、月增六個百分點，成長動能沒有放緩的跡象。',
                                         'direction': 'positive',
                                         'evidence_ids': ['fd_04'],
                                         'importance': 'high'},
                                        {'id': 'pos_03',
                                         'claim_type': 'observation',
                                         'text': '毛利率與營業利益率分別維持在六成六與五成八左右，獲利品質處在很高的水準。',
                                         'direction': 'positive',
                                         'evidence_ids': ['fd_02', 'fd_03'],
                                         'importance': 'medium'}],
                   'negative_factors': [{'id': 'neg_01',
                                         'claim_type': 'observation',
                                         'text': '外資在七月二日、九日與十三日連續調節，光是九日就賣超近一萬三千張，賣壓明顯而且持續。',
                                         'direction': 'negative',
                                         'evidence_ids': ['d_34', 'd_39', 'd_40'],
                                         'importance': 'high'},
                                        {'id': 'neg_02',
                                         'claim_type': 'inference',
                                         'text': '上漲的日子量能反而縮、下跌的日子量能才放大，代表追價意願不足，賣方比買方積極。',
                                         'direction': 'negative',
                                         'evidence_ids': ['d_33', 'd_39', 'd_40'],
                                         'importance': 'high'},
                                        {'id': 'neg_03',
                                         'claim_type': 'inference',
                                         'text': '股價已經在近一年區間的高位，上行動能卻同時轉弱，價格與動能之間出現背離。',
                                         'direction': 'negative',
                                         'evidence_ids': ['lt_03', 'd_40'],
                                         'importance': 'medium'}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '公司的獲利與營收數字非常強，但市場資金在同一段時間持續流出，基本面與籌碼面方向相反。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['fd_01', 'fd_04', 'd_39', 'd_40'],
                                           'importance': 'high'},
                                          {'id': 'div_02',
                                           'claim_type': 'limitation',
                                           'text': '檢索到的五則新聞有四則是大盤指數的即時行情快訊，與這檔個股沒有直接關聯，只有一則提到外資對本檔的調節。',
                                           'direction': 'not_applicable',
                                           'evidence_ids': ['nw_01', 'nw_02', 'nw_05'],
                                           'importance': 'medium'}],
                   'risks': [{'id': 'rk_01',
                              'risk_type': '籌碼',
                              'description': '外資近兩週幾乎每個交易日都是賣超，在股價位於近一年高位的情況下，籌碼鬆動的影響會被放大。',
                              'trigger': '外資單日賣超再度超過一萬張，且股價同步收黑',
                              'evidence_ids': ['d_34', 'd_39', 'lt_03']},
                             {'id': 'rk_02',
                              'risk_type': '量能',
                              'description': '反彈都在量能不足的情況下發生，缺乏成交量確認的上漲通常不容易延續。',
                              'trigger': '上漲日的成交量仍然低於近五日平均',
                              'evidence_ids': ['d_33', 'd_40']},
                             {'id': 'rk_03',
                              'risk_type': '評價',
                              'description': '目前的高股價已經反映很強的獲利成長，一旦單月營收的成長速度放慢，評價調整的壓力會很直接。',
                              'trigger': '單月營收年增率明顯低於前幾期',
                              'evidence_ids': ['fd_04', 'lt_03']}],
                   'watch_points': [{'id': 'wp_01',
                                     'what_to_watch': '七月營收公告',
                                     'why_it_matters': '六月營收年增將近七成，七月能否維持同樣量級，是判斷成長動能有沒有轉折最直接的指標。',
                                     'when': '八月十日前',
                                     'evidence_ids': ['fd_04']},
                                    {'id': 'wp_02',
                                     'what_to_watch': '外資連續賣超會不會中斷',
                                     'why_it_matters': '近兩週的壓力主要來自外資調節，只要這條賣超鏈沒有斷，股價就很難脫離整理。',
                                     'when': '接下來一到兩週的每日法人資料',
                                     'evidence_ids': ['d_34', 'd_39', 'd_40']},
                                    {'id': 'wp_03',
                                     'what_to_watch': '上漲日的成交量',
                                     'why_it_matters': '這段期間上漲都是量縮，只有出現量價同步放大的日子，才代表買方態度真的轉變。',
                                     'when': '接下來的每個交易日',
                                     'evidence_ids': ['d_33', 'd_40']},
                                    {'id': 'wp_04',
                                     'what_to_watch': '最新一季財報',
                                     'why_it_matters': '正式財報目前只到上一季，下一季數字能否延續逐季成長，會決定基本面優勢還在不在。',
                                     'when': '下一季財報公告',
                                     'evidence_ids': ['fd_01']}],
                   'forward_views': {'short_1_5': {'stance': 'neutral',
                                                   'reason': '價格貼著近一個月平均整理，量能與籌碼都沒有給出明確方向。',
                                                   'invalidation': '出現量價同步放大、且外資轉為買超的交易日',
                                                   'evidence_ids': ['d_40', 'd_33']},
                                     'swing_6_20': {'stance': 'mixed',
                                                    'reason': '基本面成長很強，但外資持續調節與上行動能轉弱同時存在，兩股力量互相抵銷。',
                                                    'invalidation': '外資連續三天買超，或單月營收成長明顯降速',
                                                    'evidence_ids': ['fd_04', 'd_39', 'd_40']},
                                     'medium_21_40': {'stance': 'mildly_bullish',
                                                      'reason': '獲利與營收連續多期走高，只要成長節奏不變，中期的基本面仍是主要支持。',
                                                      'invalidation': '單月營收年增率連續兩期明顯放緩，或季度獲利停止成長',
                                                      'evidence_ids': ['fd_01', 'fd_04']}},
                   'overall_stance': 'mixed',
                   'confidence': 'medium',
                   'confidence_reason': '價量、籌碼與基本面資料都完整，但基本面明顯偏多、籌碼與量能偏空，方向互相矛盾，可用新聞也多為大盤雜訊。',
                   'limitations': ['檢索到的新聞多為大盤指數快訊，其中三則是同一則盤中速報的不同時間點，對個股判斷幫助有限。',
                                   '最新正式財報為 2026 年第一季，下一季的獲利狀況尚無法確認。']}}]


def example_set_version() -> str:
    if not FEW_SHOT_EXAMPLES:
        return "none"
    canonical = json.dumps(FEW_SHOT_EXAMPLES, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]
