from __future__ import annotations

import hashlib
import json
from typing import Any, TypedDict


class FewShotExample(TypedDict):
    scenario: str
    input_payload: dict[str, Any]
    output_brief: dict[str, Any]


# 由人工蒸餾流程 curate 後填入；順序即注入順序，最典型的放最後、定案後不得重排。
# 產製來源：真實 as_of 快照（2026-07-17 curate，來源見各例 task），經人工修整與
# schema／法遵／證據完整性三重驗證（curate_golden_examples.py）。
FEW_SHOT_EXAMPLES: list[FewShotExample] = [{'scenario': '資料稀少',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2615',
                             'as_of_date': '2026-02-06'},
                    'data_inventory': {'price_volume': [{'id': 'pv_01',
                                                         'field': 'close',
                                                         'date': '2026-02-06',
                                                         'value': 73.9},
                                                        {'id': 'pv_02',
                                                         'field': 'volume_shares',
                                                         'date': '2026-02-06',
                                                         'value': 4106126},
                                                        {'id': 'pv_03',
                                                         'field': 'volume_ma5',
                                                         'date': '2026-02-06',
                                                         'value': 4454640.6},
                                                        {'id': 'pv_04',
                                                         'field': 'volume_ma20',
                                                         'date': '2026-02-06',
                                                         'value': 6390438.6}],
                                       'chip': [{'id': 'ch_01',
                                                 'field': 'foreign_net',
                                                 'date': '2026-02-06',
                                                 'value': -508664,
                                                 'streak_days': 1},
                                                {'id': 'ch_02',
                                                 'field': 'foreign_net_10d_sum',
                                                 'date': '2026-02-06',
                                                 'value': -150377},
                                                {'id': 'ch_03',
                                                 'field': 'trust_net',
                                                 'date': '2026-02-06',
                                                 'value': 78000,
                                                 'streak_days': 2}],
                                       'technical': [{'id': 'tc_02',
                                                      'field': 'kd_k',
                                                      'date': '2026-02-06',
                                                      'value': 33.47},
                                                     {'id': 'tc_03',
                                                      'field': 'macd_diff',
                                                      'date': '2026-02-06',
                                                      'value': -1.2264},
                                                     {'id': 'tc_04',
                                                      'field': 'macd_histogram',
                                                      'date': '2026-02-06',
                                                      'value': -0.0368},
                                                     {'id': 'tc_05',
                                                      'field': 'ma20',
                                                      'date': '2026-02-06',
                                                      'value': 75.83},
                                                     {'id': 'tc_06',
                                                      'field': 'ma60',
                                                      'date': '2026-02-06',
                                                      'value': 78.46},
                                                     {'id': 'tc_07',
                                                      'field': 'boll_mid20',
                                                      'date': '2026-02-06',
                                                      'value': 75.83}],
                                       'news': [],
                                       'missing_fields': []}},
  'output_brief': {'headline': '萬海股價跌破月線，量能萎縮至低檔，法人近十日累積賣超，短線偏弱整理。',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '2026年2月6日收盤73.9元，跌破月線（75.83元）與季線（78.46元），處於布林通道中軌下方。',
                                       'direction': 'negative',
                                       'evidence_ids': ['pv_01', 'tc_05', 'tc_06', 'tc_07'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '成交量僅4,106張，低於五日均量（4,454張）與二十日均量（6,390張），量能明顯不足。',
                                       'direction': 'negative',
                                       'evidence_ids': ['pv_02', 'pv_03', 'pv_04'],
                                       'importance': 'high'},
                                      {'id': 'cs_03',
                                       'claim_type': 'observation',
                                       'text': '外資單日賣超508,664張，近十日累積賣超150,377張，投信雖連兩日買超但力道有限。',
                                       'direction': 'negative',
                                       'evidence_ids': ['ch_01', 'ch_02', 'ch_03'],
                                       'importance': 'medium'}],
                   'key_reasons': [{'id': 'why_01',
                                    'claim_type': 'observation',
                                    'text': '收盤價持續低於月線與季線，均線結構呈空頭排列，顯示中期趨勢偏弱，市場信心不足。',
                                    'direction': 'negative',
                                    'evidence_ids': ['tc_05', 'tc_06', 'pv_01'],
                                    'importance': 'high'},
                                   {'id': 'why_02',
                                    'claim_type': 'observation',
                                    'text': '成交量連續低於短期均量，追價意願保守，缺乏足夠買盤支撐反彈，易形成盤跌格局。',
                                    'direction': 'negative',
                                    'evidence_ids': ['pv_02', 'pv_03', 'pv_04'],
                                    'importance': 'high'},
                                   {'id': 'why_03',
                                    'claim_type': 'observation',
                                    'text': '外資近十日累積賣超，單日亦轉為賣超，籌碼面偏弱；投信雖小幅買超但未能抵銷外資賣壓。',
                                    'direction': 'negative',
                                    'evidence_ids': ['ch_01', 'ch_02', 'ch_03'],
                                    'importance': 'medium'},
                                   {'id': 'why_04',
                                    'claim_type': 'observation',
                                    'text': 'MACD柱狀體雖收斂至-0.0368，但DIF仍為負值，KD指標處於中低檔，技術面尚未出現明確轉強訊號。',
                                    'direction': 'negative',
                                    'evidence_ids': ['tc_03', 'tc_04', 'tc_02'],
                                    'importance': 'medium'}],
                   'events': [],
                   'potential_impacts': [{'id': 'impact_01',
                                          'source_item_ids': ['why_01', 'why_02'],
                                          'text': '若成交量持續低於五日均量，股價可能沿月線下方弱勢整理，反彈空間受限。',
                                          'direction': 'negative',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'strengthens',
                                          'evidence_ids': ['pv_02', 'pv_03', 'tc_05']},
                                         {'id': 'impact_02',
                                          'source_item_ids': ['why_03'],
                                          'text': '外資若持續賣超，將加重籌碼面壓力，不利短線止穩；投信買超力道若減弱，將失去少數多方支撐。',
                                          'direction': 'negative',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'strengthens',
                                          'evidence_ids': ['ch_01', 'ch_02', 'ch_03']}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '投信連兩日買超，與外資單日及近十日累積賣超方向相反，籌碼面呈現內外資拉扯，但外資賣壓規模較大。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['ch_01', 'ch_02', 'ch_03'],
                                           'importance': 'medium'}],
                   'watch_conditions': [{'id': 'cond_01',
                                         'kind': 'confirmation',
                                         'trigger': {'metric': 'close_vs_ma20',
                                                     'operator': 'crosses_above',
                                                     'persistence_sessions': 2,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'strengthens',
                                                  'direction': 'mildly_bullish',
                                                  'within_trading_days': 5,
                                                  'text': '若收盤連續兩日站回月線之上，短線反彈力道可望增強。'},
                                         'rationale': '月線為短期多空分界，站回月線代表短線買盤回溫。',
                                         'evidence_ids': ['tc_05', 'pv_01'],
                                         'scorable': False},
                                        {'id': 'cond_02',
                                         'kind': 'invalidation',
                                         'trigger': {'metric': 'volume_vs_ma5',
                                                     'operator': 'stays_below',
                                                     'persistence_sessions': 3,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'weakens',
                                                  'direction': 'mildly_bearish',
                                                  'within_trading_days': 5,
                                                  'text': '若成交量連續三日低於五日均量，反彈動能不足，弱勢整理格局延續。'},
                                         'rationale': '量能持續低迷將限制股價反彈空間，易形成盤跌。',
                                         'evidence_ids': ['pv_02', 'pv_03'],
                                         'scorable': False}],
                   'forward_views': [{'horizon': 'short_1_5',
                                      'text': '量能不足且外資單日賣超，股價跌破月線，短期內反彈力道受限，偏向弱勢整理。',
                                      'stance': 'mildly_bearish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_01', 'why_02', 'why_03'],
                                      'evidence_ids': ['pv_01', 'pv_02', 'ch_01', 'tc_05'],
                                      'confirmation_condition_ids': ['cond_01'],
                                      'invalidation_condition_ids': ['cond_02']},
                                     {'horizon': 'swing_6_20',
                                      'text': '均線空頭排列，外資近十日累積賣超，MACD仍處負值區，若量能未回升，股價可能沿月線下方震盪。',
                                      'stance': 'mildly_bearish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_01', 'why_02', 'why_03', 'why_04'],
                                      'evidence_ids': ['tc_05', 'tc_06', 'ch_02', 'tc_03'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': ['cond_02']},
                                     {'horizon': 'medium_21_40',
                                      'text': '中期趨勢偏弱，季線持續下彎，若無明顯籌碼面改善或基本面利多，股價可能維持在季線下方整理。',
                                      'stance': 'mildly_bearish',
                                      'confidence': 'low',
                                      'basis_item_ids': ['why_01', 'why_03'],
                                      'evidence_ids': ['tc_06', 'ch_02'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': []}],
                   'thesis': {'statement': '萬海目前處於量縮價跌的弱勢整理格局，均線空頭排列且外資持續賣超，短期缺乏明確轉強訊號。',
                              'status': 'new',
                              'evidence_ids': ['pv_01', 'pv_02', 'tc_05', 'tc_06', 'ch_01', 'ch_02']},
                   'overall_stance': 'mildly_bearish',
                   'confidence': 'medium',
                   'confidence_reason': '價量、籌碼與技術指標方向一致偏弱，但投信小幅買超與MACD柱狀體收斂提供微弱多方訊號，整體證據尚稱充分。',
                   'limitations': ['近期無重大基本面新聞可供參考，僅依賴價量與籌碼數據判斷。',
                                   '投信買超力道有限，尚不足以確認內資積極承接。',
                                   'MACD柱狀體收斂幅度微小，技術面轉強訊號尚未明確。']}},
 {'scenario': '偏強一致',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2330',
                             'as_of_date': '2024-06-20'},
                    'data_inventory': {'price_volume': [{'id': 'pv_01',
                                                         'field': 'close',
                                                         'date': '2024-06-20',
                                                         'value': 981.0},
                                                        {'id': 'pv_02',
                                                         'field': 'volume_shares',
                                                         'date': '2024-06-20',
                                                         'value': 52144900},
                                                        {'id': 'pv_03',
                                                         'field': 'volume_ma5',
                                                         'date': '2024-06-20',
                                                         'value': 48357111.6}],
                                       'chip': [{'id': 'ch_01',
                                                 'field': 'foreign_net',
                                                 'date': '2024-06-20',
                                                 'value': -8939051,
                                                 'streak_days': 1},
                                                {'id': 'ch_02',
                                                 'field': 'foreign_net_10d_sum',
                                                 'date': '2024-06-20',
                                                 'value': 10319886},
                                                {'id': 'ch_03',
                                                 'field': 'trust_net',
                                                 'date': '2024-06-20',
                                                 'value': 434050,
                                                 'streak_days': 8},
                                                {'id': 'ch_04',
                                                 'field': 'dealer_net',
                                                 'date': '2024-06-20',
                                                 'value': 3283116,
                                                 'streak_days': 1}],
                                       'technical': [{'id': 'tc_01',
                                                      'field': 'rsi_5',
                                                      'date': '2024-06-20',
                                                      'value': 91.67},
                                                     {'id': 'tc_02',
                                                      'field': 'kd_k',
                                                      'date': '2024-06-20',
                                                      'value': 92.75},
                                                     {'id': 'tc_03',
                                                      'field': 'macd_diff',
                                                      'date': '2024-06-20',
                                                      'value': 36.4034},
                                                     {'id': 'tc_04',
                                                      'field': 'macd_histogram',
                                                      'date': '2024-06-20',
                                                      'value': 9.2924},
                                                     {'id': 'tc_05',
                                                      'field': 'ma20',
                                                      'date': '2024-06-20',
                                                      'value': 888.15}],
                                       'news': [{'id': 'nw_01',
                                                 'field': 'title',
                                                 'date': '2024-05-22',
                                                 'value': '股匯雙揚！台幣結束連3黑收32.275元',
                                                 'reference_only': True}],
                                       'missing_fields': []}},
  'output_brief': {'headline': '股價強勢創高站上981元，短線技術過熱但法人籌碼出現單日調節跡象。',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '6月20日收盤981元，連續兩日創歷史新高，股價沿5日線強勢上漲。',
                                       'direction': 'positive',
                                       'evidence_ids': ['pv_01', 'tc_01'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '成交量5214萬股，略高於5日均量但未明顯爆量，追價意願尚屬穩定。',
                                       'direction': 'neutral',
                                       'evidence_ids': ['pv_02', 'pv_03'],
                                       'importance': 'medium'},
                                      {'id': 'cs_03',
                                       'claim_type': 'observation',
                                       'text': '短線技術指標RSI達91.67、KD-K值92.75，雙雙進入超買區，顯示股價動能極強但潛在回調壓力升高。',
                                       'direction': 'positive',
                                       'evidence_ids': ['tc_01', 'tc_02'],
                                       'importance': 'high'}],
                   'key_reasons': [{'id': 'why_01',
                                    'claim_type': 'observation',
                                    'text': '近10日外資累計買超1032萬股，中期籌碼偏多，但6月20日單日轉為賣超894萬股，顯示外資在股價創高後出現短線調節。',
                                    'direction': 'mixed',
                                    'evidence_ids': ['ch_01', 'ch_02'],
                                    'importance': 'high'},
                                   {'id': 'why_02',
                                    'claim_type': 'observation',
                                    'text': '投信連續8日買超，自營商今日轉為買超328萬股，內資承接力道延續，與外資單日賣超形成拉扯。',
                                    'direction': 'positive',
                                    'evidence_ids': ['ch_03', 'ch_04'],
                                    'importance': 'medium'},
                                   {'id': 'why_03',
                                    'claim_type': 'observation',
                                    'text': 'MACD柱狀體持續放大至9.29，DIF與DEA差距擴大，中期動能趨勢仍強勁，支持股價沿5日線上行。',
                                    'direction': 'positive',
                                    'evidence_ids': ['tc_03', 'tc_04'],
                                    'importance': 'high'}],
                   'events': [{'id': 'event_01',
                               'event_date': '2024-05-22',
                               'recency': 'background',
                               'title': '輝達財報發布前台積電領軍創高',
                               'description': '5月22日台積電領軍帶動台股創新高，外資當日買超321億元，市場氣氛樂觀。',
                               'information_type': 'event',
                               'evidence_ids': ['nw_01'],
                               'materiality': 'medium'}],
                   'potential_impacts': [{'id': 'impact_01',
                                          'source_item_ids': ['why_01'],
                                          'text': '外資單日賣超若持續，可能引發短線獲利了結賣壓，但近10日累積買超仍大，中期偏多格局尚未破壞。',
                                          'direction': 'negative',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'weakens',
                                          'evidence_ids': ['ch_01', 'ch_02']},
                                         {'id': 'impact_02',
                                          'source_item_ids': ['cs_03'],
                                          'text': '技術指標過熱可能觸發短線震盪或回測均線支撐，但若量能未失控，整理後仍有續強機會。',
                                          'direction': 'mixed',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'unchanged',
                                          'evidence_ids': ['tc_01', 'tc_02']}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '外資今日賣超894萬股，但投信與自營商合計買超371萬股，三大法人內部方向分歧，籌碼穩定性待觀察。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['ch_01', 'ch_03', 'ch_04'],
                                           'importance': 'high'}],
                   'watch_conditions': [{'id': 'cond_01',
                                         'kind': 'confirmation',
                                         'trigger': {'metric': 'foreign_net_daily',
                                                     'operator': 'turns_positive',
                                                     'persistence_sessions': 2,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'strengthens',
                                                  'direction': 'bullish',
                                                  'within_trading_days': 5,
                                                  'text': '若外資連續兩日轉為買超，將強化短線偏多信心。'},
                                         'rationale': '外資動向為台積電主要資金推力，連續買超可確認調節結束。',
                                         'evidence_ids': ['ch_01'],
                                         'scorable': False},
                                        {'id': 'cond_02',
                                         'kind': 'risk',
                                         'trigger': {'metric': 'close_vs_ma20',
                                                     'operator': 'crosses_below',
                                                     'persistence_sessions': 1,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'weakens',
                                                  'direction': 'mildly_bearish',
                                                  'within_trading_days': 20,
                                                  'text': '若收盤跌破月線，可能暗示中期動能轉弱，需重新評估趨勢。'},
                                         'rationale': '月線為中期趨勢重要參考，跌破將改變多頭結構。',
                                         'evidence_ids': ['tc_05'],
                                         'scorable': False},
                                        {'id': 'cond_03',
                                         'kind': 'risk',
                                         'trigger': {'metric': 'volume_vs_ma5',
                                                     'operator': 'stays_below',
                                                     'persistence_sessions': 3,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'weakens',
                                                  'direction': 'neutral',
                                                  'within_trading_days': 5,
                                                  'text': '若成交量連續低於5日均量，顯示追價力道減弱，短線可能轉為整理。'},
                                         'rationale': '量能為漲勢延續關鍵，量縮不利突破高檔壓力。',
                                         'evidence_ids': ['pv_02', 'pv_03'],
                                         'scorable': False}],
                   'forward_views': [{'horizon': 'short_1_5',
                                      'text': '短線技術指標過熱且外資單日賣超，可能出現震盪或小幅回檔，但內資承接力道仍在，不至於大幅轉弱。',
                                      'stance': 'mildly_bullish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_01', 'why_02', 'cs_03'],
                                      'evidence_ids': ['ch_01', 'ch_03', 'tc_01'],
                                      'confirmation_condition_ids': ['cond_01'],
                                      'invalidation_condition_ids': ['cond_03']},
                                     {'horizon': 'swing_6_20',
                                      'text': '中期動能結構強勁，MACD持續擴張，若外資賣超未擴大且量能維持，股價有機會沿月線向上推進。',
                                      'stance': 'bullish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_03', 'why_01'],
                                      'evidence_ids': ['tc_03', 'tc_04', 'ch_02'],
                                      'confirmation_condition_ids': ['cond_01'],
                                      'invalidation_condition_ids': ['cond_02']},
                                     {'horizon': 'medium_21_40',
                                      'text': '中期偏多格局未變，但需觀察外資累積籌碼是否持續正向，以及股價能否守穩月線之上。',
                                      'stance': 'mildly_bullish',
                                      'confidence': 'low',
                                      'basis_item_ids': ['why_01', 'why_03'],
                                      'evidence_ids': ['ch_02', 'tc_05'],
                                      'confirmation_condition_ids': ['cond_01'],
                                      'invalidation_condition_ids': ['cond_02']}],
                   'thesis': {'statement': '股價強勢創高，中期動能與籌碼偏多，但短線技術過熱且外資出現單日調節，需觀察後續資金流向。',
                              'status': 'new',
                              'evidence_ids': ['pv_01', 'ch_01', 'ch_02', 'tc_01', 'tc_03']},
                   'overall_stance': 'mildly_bullish',
                   'confidence': 'medium',
                   'confidence_reason': '價量與技術指標齊備且方向一致，但籌碼面出現外資單日賣超與內資承接的分歧，降低短期判斷的確定性。',
                   'limitations': ['新聞資料僅有一筆5月22日的背景資訊，缺乏近期事件佐證。',
                                   '外資單日賣超原因不明，無法判斷為短線調節或趨勢轉變。',
                                   '技術指標超買可能導致回檔，但回檔幅度與時間無法預測。']}},
 {'scenario': '偏弱一致',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2881',
                             'as_of_date': '2025-04-10'},
                    'data_inventory': {'price_volume': [{'id': 'pv_01',
                                                         'field': 'close',
                                                         'date': '2025-04-10',
                                                         'value': 79.3},
                                                        {'id': 'pv_02',
                                                         'field': 'volume_shares',
                                                         'date': '2025-04-10',
                                                         'value': 9962966},
                                                        {'id': 'pv_03',
                                                         'field': 'volume_ma5',
                                                         'date': '2025-04-10',
                                                         'value': 27033357.6},
                                                        {'id': 'pv_04',
                                                         'field': 'volume_ma20',
                                                         'date': '2025-04-10',
                                                         'value': 18627340.5}],
                                       'chip': [{'id': 'ch_01',
                                                 'field': 'foreign_net',
                                                 'date': '2025-04-10',
                                                 'value': -1285289,
                                                 'streak_days': 3},
                                                {'id': 'ch_02',
                                                 'field': 'foreign_net_10d_sum',
                                                 'date': '2025-04-10',
                                                 'value': -52017380},
                                                {'id': 'ch_03',
                                                 'field': 'trust_net',
                                                 'date': '2025-04-10',
                                                 'value': 0},
                                                {'id': 'ch_04',
                                                 'field': 'dealer_net',
                                                 'date': '2025-04-10',
                                                 'value': 92998,
                                                 'streak_days': 2}],
                                       'technical': [{'id': 'tc_01',
                                                      'field': 'rsi_5',
                                                      'date': '2025-04-10',
                                                      'value': 42.62},
                                                     {'id': 'tc_02',
                                                      'field': 'kd_k',
                                                      'date': '2025-04-10',
                                                      'value': 23.93},
                                                     {'id': 'tc_03',
                                                      'field': 'macd_diff',
                                                      'date': '2025-04-10',
                                                      'value': -3.34},
                                                     {'id': 'tc_04',
                                                      'field': 'macd_histogram',
                                                      'date': '2025-04-10',
                                                      'value': -1.3339},
                                                     {'id': 'tc_05',
                                                      'field': 'ma20',
                                                      'date': '2025-04-10',
                                                      'value': 86.51},
                                                     {'id': 'tc_06',
                                                      'field': 'ma60',
                                                      'date': '2025-04-10',
                                                      'value': 90.08},
                                                     {'id': 'tc_07',
                                                      'field': 'boll_mid20',
                                                      'date': '2025-04-10',
                                                      'value': 86.51},
                                                     {'id': 'tc_09',
                                                      'field': 'boll_lower20',
                                                      'date': '2025-04-10',
                                                      'value': 76.44}],
                                       'news': [],
                                       'missing_fields': []}},
  'output_brief': {'headline': '富邦金急跌後強彈，外資連賣壓力未解，短線反彈續航力待考驗',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '4月10日收盤79.3元，單日漲幅7.2元(+9.99%)，但股價仍遠低於月線86.51元與季線90.08元，處於急跌後的反彈階段。',
                                       'direction': 'positive',
                                       'evidence_ids': ['pv_01', 'tc_05', 'tc_06'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '4月10日成交量僅996萬股，遠低於五日均量2703萬股與二十日均量1862萬股，顯示反彈日追價意願保守，量能明顯不足。',
                                       'direction': 'negative',
                                       'evidence_ids': ['pv_02', 'pv_03', 'pv_04'],
                                       'importance': 'high'},
                                      {'id': 'cs_03',
                                       'claim_type': 'observation',
                                       'text': 'MACD柱狀體仍為-1.33，DIF '
                                               '-3.34持續低於零軸，中長期動能偏弱；KD-K值23.93處於低檔區，RSI-5回升至42.62，短線出現超賣後修復跡象。',
                                       'direction': 'mixed',
                                       'evidence_ids': ['tc_01', 'tc_02', 'tc_03', 'tc_04'],
                                       'importance': 'high'}],
                   'key_reasons': [{'id': 'why_01',
                                    'claim_type': 'observation',
                                    'text': '4月7日至9日連續三天重挫（78.9→77.9→72.1），累計跌幅逾20%，主要受全球關稅衝擊與系統性賣壓影響，4月10日出現技術性強彈。',
                                    'direction': 'negative',
                                    'evidence_ids': ['pv_01', 'tc_05', 'tc_06'],
                                    'importance': 'high'},
                                   {'id': 'why_02',
                                    'claim_type': 'observation',
                                    'text': '外資近十日累計賣超高達5201萬張，4月10日仍賣超128.5萬張，連續三日賣超，顯示外資賣壓尚未解除，反彈日並未見到外資轉向承接。',
                                    'direction': 'negative',
                                    'evidence_ids': ['ch_01', 'ch_02'],
                                    'importance': 'high'},
                                   {'id': 'why_03',
                                    'claim_type': 'observation',
                                    'text': '投信4月10日買賣超為零，自營商小幅買超9.3萬張，整體法人合計仍賣超119.2萬張，缺乏主力資金進場支撐反彈。',
                                    'direction': 'negative',
                                    'evidence_ids': ['ch_03', 'ch_04'],
                                    'importance': 'medium'},
                                   {'id': 'why_04',
                                    'claim_type': 'inference',
                                    'text': '股價已跌破布林帶下緣76.44元後拉回，但收盤79.3元仍在下緣附近，技術面顯示波動極大，尚未回到常態區間。',
                                    'direction': 'mixed',
                                    'evidence_ids': ['tc_07', 'tc_09'],
                                    'importance': 'medium'}],
                   'events': [{'id': 'event_01',
                               'event_date': '2025-04-07',
                               'recency': 'recent',
                               'title': '全球關稅衝擊引發金控股重挫',
                               'description': '4月7日富邦金以跌停價78.9元開盤並鎖死，隨後兩日續跌至72.1元，三個交易日累計跌幅逾20%，為近年罕見的急跌走勢。',
                               'information_type': 'event',
                               'evidence_ids': ['pv_01', 'tc_05'],
                               'materiality': 'high'}],
                   'potential_impacts': [{'id': 'impact_01',
                                          'source_item_ids': ['event_01'],
                                          'text': '急跌後雖出現單日強彈，但外資累積賣壓龐大，若外資未轉向買超，反彈可能僅為短線技術性修正，持續性存疑。',
                                          'direction': 'negative',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'weakens',
                                          'evidence_ids': ['ch_01', 'ch_02']},
                                         {'id': 'impact_02',
                                          'source_item_ids': ['why_02', 'why_03'],
                                          'text': '反彈日量能萎縮，顯示市場觀望氣氛濃厚，若後續無法補量，股價可能再次回測前低。',
                                          'direction': 'negative',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'weakens',
                                          'evidence_ids': ['pv_02', 'pv_03']}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '4月10日股價強彈近10%，但外資仍賣超128.5萬張，價格方向與主力資金流向明顯背離，反彈的可靠性存疑。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['pv_01', 'ch_01'],
                                           'importance': 'high'},
                                          {'id': 'div_02',
                                           'claim_type': 'conflict',
                                           'text': 'KD指標處於低檔、RSI回升，短線技術面暗示超賣修復；但MACD中長期動能仍深度負值，短多與中空訊號並存。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['tc_01', 'tc_02', 'tc_03', 'tc_04'],
                                           'importance': 'medium'}],
                   'watch_conditions': [{'id': 'cond_01',
                                         'kind': 'confirmation',
                                         'trigger': {'metric': 'foreign_net_daily',
                                                     'operator': 'turns_positive',
                                                     'persistence_sessions': 2,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'strengthens',
                                                  'direction': 'mildly_bullish',
                                                  'within_trading_days': 5,
                                                  'text': '若外資連續兩日轉為買超，將強化反彈的可信度與續航力。'},
                                         'rationale': '外資為主要賣壓來源，轉向買超代表賣壓緩解。',
                                         'evidence_ids': ['ch_01', 'ch_02'],
                                         'scorable': False},
                                        {'id': 'cond_02',
                                         'kind': 'invalidation',
                                         'trigger': {'metric': 'volume_vs_ma5',
                                                     'operator': 'stays_below',
                                                     'persistence_sessions': 3,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'weakens',
                                                  'direction': 'mildly_bearish',
                                                  'within_trading_days': 5,
                                                  'text': '若成交量持續低於五日均量，反彈動能不足，股價可能再度走弱。'},
                                         'rationale': '量能不足代表追價意願低落，反彈結構不扎實。',
                                         'evidence_ids': ['pv_02', 'pv_03'],
                                         'scorable': False},
                                        {'id': 'cond_03',
                                         'kind': 'confirmation',
                                         'trigger': {'metric': 'close_vs_ma20',
                                                     'operator': 'crosses_above',
                                                     'persistence_sessions': 1,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'strengthens',
                                                  'direction': 'mildly_bullish',
                                                  'within_trading_days': 20,
                                                  'text': '若收盤站回月線之上，代表短線趨勢有轉強可能。'},
                                         'rationale': '月線為短期多空分界，站回月線才能確認反彈升級為回升。',
                                         'evidence_ids': ['tc_05'],
                                         'scorable': False}],
                   'forward_views': [{'horizon': 'short_1_5',
                                      'text': '急跌後出現強彈，但量能不足且外資仍賣超，短線可能維持區間震盪，反彈續航力有限。',
                                      'stance': 'mildly_bearish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_02', 'why_03', 'div_01'],
                                      'evidence_ids': ['pv_02', 'ch_01', 'tc_01'],
                                      'confirmation_condition_ids': ['cond_01'],
                                      'invalidation_condition_ids': ['cond_02']},
                                     {'horizon': 'swing_6_20',
                                      'text': '若外資賣壓未緩解且量能持續低迷，股價可能在反彈後再度回測前波低點，整體走勢偏弱。',
                                      'stance': 'bearish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_02', 'impact_01'],
                                      'evidence_ids': ['ch_02', 'tc_03', 'tc_04'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': ['cond_01', 'cond_03']},
                                     {'horizon': 'medium_21_40',
                                      'text': '股價遠低於季線90.08元，MACD中長期動能深度負值，若無重大利多或法人回補，中期趨勢仍偏空整理。',
                                      'stance': 'bearish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_01', 'why_02'],
                                      'evidence_ids': ['tc_03', 'tc_04', 'tc_06'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': ['cond_03']}],
                   'thesis': {'statement': '富邦金遭系統性賣壓重挫後出現技術性強彈，但外資累積賣壓龐大且反彈量能不足，反彈結構尚不扎實，中期趨勢仍偏弱。',
                              'status': 'new',
                              'evidence_ids': ['pv_01', 'pv_02', 'ch_01', 'ch_02', 'tc_03', 'tc_04']},
                   'overall_stance': 'mildly_bearish',
                   'confidence': 'medium',
                   'confidence_reason': '價量、籌碼、技術三類資料齊備且方向大致一致：股價急跌後反彈但量能不足，外資持續賣超，中長期動能偏弱。短線KD/RSI出現修復訊號與MACD偏空形成矛盾，但整體證據指向反彈結構不穩，故信心為中等。',
                   'limitations': ['rag_news 提供的五則新聞均為2023-2024年舊聞，與當前股價走勢無直接關聯，無法作為分析依據。',
                                   '4月10日成交量僅996萬股，可能受漲停限制影響，無法完全反映市場真實供需。',
                                   '缺乏近期公司基本面或產業事件資訊，僅能依賴價量與籌碼數據進行技術面判斷。']}},
 {'scenario': '多空混合',
  'input_payload': {'task': {'type': 'stock_behavior_text_brief',
                             'symbol': '2330',
                             'as_of_date': '2025-05-05'},
                    'data_inventory': {'price_volume': [{'id': 'pv_01',
                                                         'field': 'close',
                                                         'date': '2025-05-05',
                                                         'value': 938.0},
                                                        {'id': 'pv_02',
                                                         'field': 'volume_shares',
                                                         'date': '2025-05-05',
                                                         'value': 56516129},
                                                        {'id': 'pv_03',
                                                         'field': 'volume_ma5',
                                                         'date': '2025-05-05',
                                                         'value': 40078758.6},
                                                        {'id': 'pv_04',
                                                         'field': 'volume_ma20',
                                                         'date': '2025-05-05',
                                                         'value': 49453367.4}],
                                       'chip': [{'id': 'ch_01',
                                                 'field': 'foreign_net',
                                                 'date': '2025-05-05',
                                                 'value': 13643152,
                                                 'streak_days': 8},
                                                {'id': 'ch_02',
                                                 'field': 'foreign_net_10d_sum',
                                                 'date': '2025-05-05',
                                                 'value': 91743061},
                                                {'id': 'ch_03',
                                                 'field': 'trust_net',
                                                 'date': '2025-05-05',
                                                 'value': -181047,
                                                 'streak_days': 1},
                                                {'id': 'ch_04',
                                                 'field': 'dealer_net',
                                                 'date': '2025-05-05',
                                                 'value': -3685673,
                                                 'streak_days': 5}],
                                       'technical': [{'id': 'tc_01',
                                                      'field': 'rsi_5',
                                                      'date': '2025-05-05',
                                                      'value': 72.32},
                                                     {'id': 'tc_02',
                                                      'field': 'kd_k',
                                                      'date': '2025-05-05',
                                                      'value': 89.91},
                                                     {'id': 'tc_03',
                                                      'field': 'macd_diff',
                                                      'date': '2025-05-05',
                                                      'value': -5.3626},
                                                     {'id': 'tc_04',
                                                      'field': 'macd_histogram',
                                                      'date': '2025-05-05',
                                                      'value': 15.7505},
                                                     {'id': 'tc_05',
                                                      'field': 'ma20',
                                                      'date': '2025-05-05',
                                                      'value': 868.3},
                                                     {'id': 'tc_06',
                                                      'field': 'ma60',
                                                      'date': '2025-05-05',
                                                      'value': 971.5},
                                                     {'id': 'tc_08',
                                                      'field': 'boll_upper20',
                                                      'date': '2025-05-05',
                                                      'value': 946.96}],
                                       'news': [],
                                       'missing_fields': []}},
  'output_brief': {'headline': '台積電急彈後短線過熱，外資連八買但自營商連五賣，月線乖離大需消化',
                   'current_status': [{'id': 'cs_01',
                                       'claim_type': 'observation',
                                       'text': '5月5日收盤938元，較前一日下跌12元，但仍遠高於月線868.3元與季線971.5元，處於月線之上、季線之下的夾層位置。',
                                       'direction': 'mixed',
                                       'evidence_ids': ['pv_01', 'tc_05', 'tc_06'],
                                       'importance': 'high'},
                                      {'id': 'cs_02',
                                       'claim_type': 'observation',
                                       'text': '成交量56516張，明顯高於五日均量40079張，但低於二十日均量49453張，顯示追價意願存在但尚未全面放大。',
                                       'direction': 'neutral',
                                       'evidence_ids': ['pv_02', 'pv_03', 'pv_04'],
                                       'importance': 'medium'},
                                      {'id': 'cs_03',
                                       'claim_type': 'observation',
                                       'text': '短線技術指標過熱：5日RSI達72.32，KD-K值89.91進入超買區，MACD柱狀體雖仍為正但DIF仍為負值，反彈動能強但結構尚未完全翻多。',
                                       'direction': 'positive',
                                       'evidence_ids': ['tc_01', 'tc_02', 'tc_03', 'tc_04'],
                                       'importance': 'high'}],
                   'key_reasons': [{'id': 'why_01',
                                    'claim_type': 'inference',
                                    'text': '外資連續8日買超，近十日累計買超達9174萬股，是這波從4月低點反彈的主要推力，顯示外資在急跌後積極回補。',
                                    'direction': 'positive',
                                    'evidence_ids': ['ch_01', 'ch_02'],
                                    'importance': 'high'},
                                   {'id': 'why_02',
                                    'claim_type': 'conflict',
                                    'text': '自營商連續5日賣超，5月5日單日賣超3685張，與外資方向相反，形成籌碼面拉扯，並非全市場一致看多。',
                                    'direction': 'negative',
                                    'evidence_ids': ['ch_04'],
                                    'importance': 'medium'},
                                   {'id': 'why_03',
                                    'claim_type': 'observation',
                                    'text': '收盤價938元已觸及布林帶上軌946.96元附近，月線乖離約8%，短線漲多後技術面存在回測月線的壓力。',
                                    'direction': 'negative',
                                    'evidence_ids': ['tc_05', 'tc_08', 'pv_01'],
                                    'importance': 'high'},
                                   {'id': 'why_04',
                                    'claim_type': 'observation',
                                    'text': 'MACD柱狀體連續擴張至15.75，為近半年最高，但DIF仍為-5.36，表示中長期均線結構尚未翻正，反彈格局仍屬修正而非趨勢反轉。',
                                    'direction': 'mixed',
                                    'evidence_ids': ['tc_03', 'tc_04'],
                                    'importance': 'medium'}],
                   'events': [{'id': 'event_01',
                               'event_date': '2025-05-02',
                               'recency': 'recent',
                               'title': '5月2日單日大漲42元，外資單日買超2571萬股創近期新高',
                               'description': '5月2日台積電收盤950元，單日漲幅4.6%，外資當日淨買超2571萬股，為近三個月最大單日買超量，帶動股價一舉突破月線與布林上軌。',
                               'information_type': 'event',
                               'evidence_ids': ['pv_01', 'ch_01', 'tc_05'],
                               'materiality': 'high'},
                              {'id': 'event_02',
                               'event_date': '2025-04-07',
                               'recency': 'background',
                               'title': '4月7日至9日關稅衝擊急跌，三日內從942元跌至785元',
                               'description': '受美國關稅政策衝擊，台積電4月7日單日跌94元至848元，4月9日最低觸及780元，三個交易日累計跌幅逾16%，隨後展開反彈。',
                               'information_type': 'event',
                               'evidence_ids': ['pv_01', 'tc_05'],
                               'materiality': 'high'}],
                   'potential_impacts': [{'id': 'impact_01',
                                          'source_item_ids': ['event_01', 'why_01'],
                                          'text': '外資連八買的力道若持續，短期內可望支撐股價在月線之上整理，但自營商連五賣顯示內資逢高調節，可能限制上方空間。',
                                          'direction': 'mixed',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'strengthens',
                                          'evidence_ids': ['ch_01', 'ch_04']},
                                         {'id': 'impact_02',
                                          'source_item_ids': ['why_03', 'cs_03'],
                                          'text': '短線技術指標過熱且觸及布林上軌，若成交量無法進一步放大至二十日均量之上，可能觸發技術性回檔，回測月線。',
                                          'direction': 'negative',
                                          'time_horizon': 'short',
                                          'thesis_effect': 'weakens',
                                          'evidence_ids': ['tc_01', 'tc_02', 'tc_08', 'pv_04']},
                                         {'id': 'impact_03',
                                          'source_item_ids': ['event_02', 'why_04'],
                                          'text': '4月初的急跌造成季線仍持續下彎，MACD '
                                                  'DIF尚未翻正，中長期均線結構需要時間修復，21-40日內反彈可能遭遇季線反壓。',
                                          'direction': 'negative',
                                          'time_horizon': 'medium',
                                          'thesis_effect': 'weakens',
                                          'evidence_ids': ['tc_03', 'tc_06']}],
                   'source_divergences': [{'id': 'div_01',
                                           'claim_type': 'conflict',
                                           'text': '外資近十日累計買超9174萬股積極做多，但自營商連續5日賣超且投信5月5日轉賣，內外資方向明顯分歧。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['ch_01', 'ch_02', 'ch_03', 'ch_04'],
                                           'importance': 'high'},
                                          {'id': 'div_02',
                                           'claim_type': 'conflict',
                                           'text': '短線RSI與KD指標顯示過熱，但MACD柱狀體仍在擴張，動能指標之間對續航力給出不同訊號。',
                                           'direction': 'mixed',
                                           'evidence_ids': ['tc_01', 'tc_02', 'tc_04'],
                                           'importance': 'medium'}],
                   'watch_conditions': [{'id': 'cond_01',
                                         'kind': 'invalidation',
                                         'trigger': {'metric': 'volume_vs_ma20',
                                                     'operator': 'stays_below',
                                                     'persistence_sessions': 3,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'weakens',
                                                  'direction': 'mildly_bearish',
                                                  'within_trading_days': 5,
                                                  'text': '若成交量連續3日低於二十日均量，反彈續航力不足，短線可能轉弱回測月線。'},
                                         'rationale': '目前量能僅略高於五日均量但低於二十日均量，若無法進一步放大，表示追價意願不足。',
                                         'evidence_ids': ['pv_02', 'pv_04'],
                                         'scorable': False},
                                        {'id': 'cond_02',
                                         'kind': 'risk',
                                         'trigger': {'metric': 'close_vs_ma60',
                                                     'operator': 'crosses_below',
                                                     'persistence_sessions': 1,
                                                     'event_ref': None},
                                         'then': {'effect_on_view': 'invalidates',
                                                  'direction': 'bearish',
                                                  'within_trading_days': 20,
                                                  'text': '若收盤跌破季線，表示反彈結構遭破壞，中期需重新評估支撐。'},
                                         'rationale': '季線971.5元仍在下彎，若股價無法站回季線之上，中期偏空格局未變。',
                                         'evidence_ids': ['tc_06', 'pv_01'],
                                         'scorable': False}],
                   'forward_views': [{'horizon': 'short_1_5',
                                      'text': '短線技術指標過熱，RSI與KD皆在超買區，且收盤接近布林上軌，1-5日內可能出現技術性回檔或高檔震盪，但外資買盤仍提供下檔支撐。',
                                      'stance': 'mildly_bearish',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_03', 'cs_03', 'div_02'],
                                      'evidence_ids': ['tc_01', 'tc_02', 'tc_08', 'ch_01'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': ['cond_01']},
                                     {'horizon': 'swing_6_20',
                                      'text': '6-20日內，外資買超力道與自營商賣壓的拉扯將主導方向，若能守穩月線且MACD '
                                              'DIF翻正，反彈可望延續；否則可能進入月線與季線間的區間整理。',
                                      'stance': 'mixed',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_01', 'why_02', 'div_01', 'impact_01'],
                                      'evidence_ids': ['ch_01', 'ch_02', 'ch_04', 'tc_03'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': ['cond_01']},
                                     {'horizon': 'medium_21_40',
                                      'text': '21-40日內，季線仍為關鍵反壓，MACD '
                                              'DIF尚未翻正顯示中長期趨勢偏弱，反彈要轉為多頭趨勢需時間累積，目前偏向在月線與季線之間築底。',
                                      'stance': 'neutral',
                                      'confidence': 'medium',
                                      'basis_item_ids': ['why_04', 'impact_03', 'event_02'],
                                      'evidence_ids': ['tc_03', 'tc_06', 'tc_05'],
                                      'confirmation_condition_ids': [],
                                      'invalidation_condition_ids': ['cond_02']}],
                   'thesis': {'statement': '台積電自4月關稅衝擊急跌後，在外資連續大買下強彈至月線之上，但短線過熱且內外資分歧，目前處於急彈後的消化整理階段，中期趨勢尚未翻多。',
                              'status': 'new',
                              'evidence_ids': ['ch_01',
                                               'ch_02',
                                               'ch_04',
                                               'tc_01',
                                               'tc_02',
                                               'tc_03',
                                               'tc_05',
                                               'tc_06']},
                   'overall_stance': 'mixed',
                   'confidence': 'medium',
                   'confidence_reason': '價量、籌碼、技術三類資料齊備，但內外資方向分歧、短線過熱與中線結構偏弱並存，訊號互相矛盾，因此信心度為中等。',
                   'limitations': ['rag_news提供的五篇新聞日期均為2024年以前，與as_of_date '
                                   '2025-05-05差距超過30天，僅列為背景參考，未用於方向判斷。',
                                   '缺乏2025年4-5月的基本面或產業新聞，無法評估關稅事件後續發展與基本面變化。',
                                   '自營商連續賣超的原因（避險或獲利了結）無法從現有資料判定，僅能呈現分歧事實。']}}]


def example_set_version() -> str:
    if not FEW_SHOT_EXAMPLES:
        return "none"
    canonical = json.dumps(FEW_SHOT_EXAMPLES, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]
