import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import { ChatInput } from './ChatInput';
const noop = () => {};
const waiting = renderToStaticMarkup(<ChatInput onSend={noop} disabled onStop={noop} />);
assert.match(waiting, /停止接收/);
assert.match(waiting, /<textarea[^>]* disabled=""/);
assert.doesNotMatch(waiting, /後端.*已停止|費用.*停止/);
const stopped = renderToStaticMarkup(<ChatInput onSend={noop} disabled={false} stopNotice />);
assert.match(stopped, /role="status"/);
assert.match(stopped, /已停止接收，後端可能仍在處理/);
assert.doesNotMatch(stopped, /<textarea[^>]* disabled=""|停止接收<\/button>/);
assert.doesNotMatch(renderToStaticMarkup(<ChatInput onSend={noop} disabled={false} />), /已停止接收|停止接收<\/button>/);
console.log('Chat stop UI passed: waiting control, enabled input after stop, explicit backend limitation, no idle stop control.');
