import assert from 'node:assert/strict';
import { AUTH_CHANGE_EVENT, clearAuth, getToken, getStoredUser, isAuthSessionBoundary, setAuth, updateStoredUser } from './storage';
import type { UserPublic } from '../types/api';
const values = new Map<string, string>();
const local = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) };
const fakeWindow = new EventTarget();
Object.defineProperty(globalThis, 'window', { configurable: true, value: fakeWindow });
Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: local });
let logout = false;
fakeWindow.addEventListener(AUTH_CHANGE_EVENT, (event) => { logout = Boolean((event as CustomEvent).detail?.logout); });
const user = (id: number): UserPublic => ({ id, email: `fixture-${id}@example.com`, display_name: 'Fixture' });
setAuth('fixture-token', user(1));
assert.equal(getToken(), 'fixture-token');
assert.equal(getStoredUser()?.id, 1);
updateStoredUser({ ...user(1), display_name: 'Updated' });
assert.equal(getStoredUser()?.display_name, 'Updated');
assert.equal(logout, false);
clearAuth();
assert.equal(getToken(), null);
assert.equal(getStoredUser(), null);
assert.equal(logout, true);
assert.equal(isAuthSessionBoundary({ key: 'topictest_access_token', oldValue: 'token', newValue: null }), true);
assert.equal(isAuthSessionBoundary({ key: 'topictest_access_token', oldValue: 'token', newValue: 'refreshed' }), false);
assert.equal(isAuthSessionBoundary({ key: 'topictest_user', oldValue: JSON.stringify(user(1)), newValue: JSON.stringify(user(2)) }), true);
assert.equal(isAuthSessionBoundary({ key: 'topictest_user', oldValue: JSON.stringify(user(1)), newValue: JSON.stringify({ ...user(1), display_name: 'Updated' }) }), false);
assert.equal(isAuthSessionBoundary({ key: null, oldValue: null, newValue: null }), true);
console.log('Auth storage passed: account changes, logout events, and cross-tab boundaries.');
